#!/usr/bin/env python3
"""Add batch 1 of ~60 new animals to animals.json (IDs 72-131)."""

import json
from pathlib import Path

DATA_PATH = Path(__file__).resolve().parent.parent / "src" / "data" / "animals.json"

def status_code(status):
    return {
        "LC": "Least Concern", "NT": "Near Threatened", "VU": "Vulnerable",
        "EN": "Endangered", "CR": "Critically Endangered", "DD": "Data Deficient"
    }.get(status, status)

def a(id, slug, common, sci, tax, iucn, desc, hab, diet, life, wt, regions, coords, facts, wiki, country, emoji, flag, region, classification, pop):
    return {
        "id": str(id), "slug": slug, "commonName": common, "scientificName": sci,
        "taxonomy": tax, "iucnStatus": iucn, "description": desc,
        "habitat": hab, "diet": diet, "lifespan": life, "weight": wt,
        "nativeRegions": regions, "coordinates": coords, "images": [],
        "funFacts": facts, "wikiUrl": wiki, "iucnUrl": "",
        "updatedAt": "2026-04-17T00:00:00Z",
        "country": country, "emoji": emoji, "flag": flag, "region": region,
        "classification": classification, "conservationStatus": status_code(iucn),
        "population": pop, "indigenous": True, "habitatOld": ", ".join(hab)
    }

animals = [
    # AFRICA (72-89)
    a(72, "nile-crocodile", "Nile Crocodile", "Crocodylus niloticus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Crocodilia","family":"Crocodylidae","genus":"Crocodylus"},
      "LC", "Africa's largest freshwater predator found across sub-Saharan Africa.",
      ["freshwater rivers","lakes","marshes"], "Carnivore",
      {"min":50,"max":100,"unit":"years"}, {"min":200,"max":750,"unit":"kg"},
      ["Africa"], [{"lat":-1.3,"lng":36.8,"label":"Kenya"}],
      ["Can hold their breath underwater for up to 2 hours when resting.","Have the strongest bite force ever measured in a living animal.","Females carry hatchlings in their mouths to the water.","Can grow up to 5 meters (16 feet) long.","Remained largely unchanged for millions of years."],
      "https://en.wikipedia.org/wiki/Nile_crocodile", "Kenya", "🐊", "🇰🇪", "Africa", "Reptile", "~250,000-500,000"),

    a(73, "african-grey-parrot", "African Grey Parrot", "Psittacus erithacus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Psittaciformes","family":"Psittacidae","genus":"Psittacus"},
      "EN", "One of the most intelligent bird species, known for exceptional ability to mimic human speech.",
      ["lowland rainforest","forest edges"], "Omnivore",
      {"min":40,"max":60,"unit":"years"}, {"min":0.3,"max":0.6,"unit":"kg"},
      ["Africa"], [{"lat":-4.3,"lng":15.3,"label":"Democratic Republic of Congo"}],
      ["Can learn vocabularies of over 1000 words.","Ranked among the most intelligent bird species on Earth.","Population has declined over 50% in the last three generations.","They mate for life and form strong pair bonds.","Capable of understanding concepts like color and shape."],
      "https://en.wikipedia.org/wiki/African_grey_parrot", "Democratic Republic of Congo", "🦜", "🇨🇩", "Africa", "Bird", "~680,000-13,000,000"),

    a(74, "okapi", "Okapi", "Okapia johnstoni",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Giraffidae","genus":"Okapia"},
      "EN", "The 'forest giraffe' endemic to the dense tropical rainforests of the Democratic Republic of Congo.",
      ["dense tropical rainforest"], "Herbivore",
      {"min":20,"max":30,"unit":"years"}, {"min":200,"max":350,"unit":"kg"},
      ["Africa"], [{"lat":1.5,"lng":27.5,"label":"Democratic Republic of Congo"}],
      ["Closest living relative is the giraffe, not the zebra.","Striped hindquarters help calves follow mothers through dense forest.","Their tongue is long enough to wash their own eyelids.","First described to Western science in 1901.","Was unknown to the outside world until the late 19th century."],
      "https://en.wikipedia.org/wiki/Okapi", "Democratic Republic of Congo", "🦏", "🇨🇩", "Africa", "Mammal", "~35,000-50,000"),

    a(75, "shoebill", "Shoebill", "Balaeniceps rex",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Pelecaniformes","family":"Balaenicipitidae","genus":"Balaeniceps"},
      "VU", "A massive prehistoric-looking stork found in the swamps of central tropical Africa.",
      ["swamps","marshes","wetlands"], "Carnivore",
      {"min":30,"max":35,"unit":"years"}, {"min":4,"max":7,"unit":"kg"},
      ["Africa"], [{"lat":-15.4,"lng":28.3,"label":"Zambia"}],
      ["Named for its enormous shoe-shaped bill.","Can stand perfectly still for hours while hunting fish.","Sometimes called the 'whale-headed stork'.","One of the most sought-after birds by birdwatchers.","Their deep booming calls sound like a machine gun."],
      "https://en.wikipedia.org/wiki/Shoebill", "Zambia", "🦢", "🇿🇲", "Africa", "Bird", "~5,000-8,000"),

    a(76, "mandrill", "Mandrill", "Mandrillus sphinx",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Cercopithecidae","genus":"Mandrillus"},
      "VU", "The world's largest monkey, famous for the male's vivid blue and red facial coloration.",
      ["tropical rainforest","subtropical forest"], "Omnivore",
      {"min":20,"max":30,"unit":"years"}, {"min":20,"max":35,"unit":"kg"},
      ["Africa"], [{"lat":6.0,"lng":12.0,"label":"Cameroon"}],
      ["Males have the most colorful faces of any mammal.","Their facial colors brighten when excited.","Live in groups called 'hordes' that can number over 600.","More closely related to baboons than to great apes.","Have cheek pouches that can store food while foraging."],
      "https://en.wikipedia.org/wiki/Mandrill", "Cameroon", "🐵", "🇨🇲", "Africa", "Mammal", "~50,000-100,000"),

    a(77, "giant-ground-pangolin", "Giant Ground Pangolin", "Smutsia gigantea",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Pholidota","family":"Manidae","genus":"Smutsia"},
      "CR", "The largest pangolin species, heavily poached for its scales used in traditional medicine.",
      ["tropical forest","savanna woodland"], "Carnivore",
      {"min":15,"max":20,"unit":"years"}, {"min":30,"max":33,"unit":"kg"},
      ["Africa"], [{"lat":6.0,"lng":12.0,"label":"Cameroon"}],
      ["The only mammals entirely covered in keratin scales.","Can consume up to 70 million ants and termites per year.","Their tongues can be longer than their entire bodies when extended.","Roll into a tight ball when threatened — impenetrable to most predators.","Pangolin trafficking is estimated at over 1 million animals per decade."],
      "https://en.wikipedia.org/wiki/Giant_pangolin", "Cameroon", "🦎", "🇨🇲", "Africa", "Mammal", "Unknown (declining rapidly)"),

    a(78, "aardvark", "Aardvark", "Orycteropus afer",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Tubulidentata","family":"Orycteropodidae","genus":"Orycteropus"},
      "LC", "Africa's only living species of the order Tubulidentata, a specialized ant and termite eater.",
      ["savanna","grassland","woodland"], "Carnivore",
      {"min":10,"max":23,"unit":"years"}, {"min":50,"max":82,"unit":"kg"},
      ["Africa"], [{"lat":-30.6,"lng":22.9,"label":"South Africa"}],
      ["The name means 'earth pig' in Afrikaans.","Their powerful claws can dig through termite mounds as hard as concrete.","Have no close living relatives — in their own unique order.","Can dig a meter of tunnel in just 5 minutes.","Their teeth grow continuously throughout life and have no enamel."],
      "https://en.wikipedia.org/wiki/Aardvark", "South Africa", "🦔", "🇿🇦", "Africa", "Mammal", "Unknown (widespread)"),

    a(79, "fossa", "Fossa", "Cryptoprocta ferox",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Eupleridae","genus":"Cryptoprocta"},
      "EN", "Madagascar's top predator, resembling a cross between a cat and a mongoose.",
      ["tropical forest"], "Carnivore",
      {"min":15,"max":20,"unit":"years"}, {"min":7,"max":12,"unit":"kg"},
      ["Africa"], [{"lat":-18.9,"lng":47.5,"label":"Madagascar"}],
      ["Madagascar's largest native carnivore.","More closely related to mongooses than cats.","Can hunt lemurs in trees — 90% arboreal when hunting.","Flexible ankles allow them to climb down trees head-first.","Classified as a cat-like carnivore despite not being a cat."],
      "https://en.wikipedia.org/wiki/Fossa_(animal)", "Madagascar", "🐱", "🇲🇬", "Africa", "Mammal", "~2,600"),

    a(80, "gelada-baboon", "Gelada", "Theropithecus gelada",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Cercopithecidae","genus":"Theropithecus"},
      "NT", "The only grazing primate, found only in the Ethiopian Highlands.",
      ["alpine grassland","montane meadow"], "Herbivore",
      {"min":15,"max":20,"unit":"years"}, {"min":15,"max":20,"unit":"kg"},
      ["Africa"], [{"lat":9.0,"lng":38.7,"label":"Ethiopia"}],
      ["The only primate that primarily grazes on grass.","Have a distinctive hourglass-shaped red patch on their chest.","Males have impressive manes resembling a lion's.","The most terrestrial primate besides humans and baboons.","Live in the largest groups of any non-human primate (up to 800)."],
      "https://en.wikipedia.org/wiki/Gelada", "Ethiopia", "🐒", "🇪🇹", "Africa", "Mammal", "~200,000-500,000"),

    a(81, "caracal", "Caracal", "Caracal caracal",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Caracal"},
      "LC", "A striking medium-sized wild cat with distinctive tufted ears, found across Africa and Asia.",
      ["savanna","woodland","semi-desert"], "Carnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":8,"max":20,"unit":"kg"},
      ["Africa"], [{"lat":-30.6,"lng":22.9,"label":"South Africa"}],
      ["Can leap up to 3 meters (10 feet) in the air to catch birds.","Their ear tufts can be up to 4.5 cm long.","Once trained for hunting in India and Persia.","Among the fastest small cats — can sprint at 80 km/h.","Name comes from the Turkish word 'karakulak' meaning 'black ear'."],
      "https://en.wikipedia.org/wiki/Caracal", "South Africa", "🐱", "🇿🇦", "Africa", "Mammal", "Unknown (widespread)"),

    a(82, "secretary-bird", "Secretary Bird", "Sagittarius serpentarius",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Accipitriformes","family":"Sagittariidae","genus":"Sagittarius"},
      "VU", "A large bird of prey that hunts on foot across African savannas, famous for stomping snakes to death.",
      ["savanna","grassland","shrubland"], "Carnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":2.5,"max":4.3,"unit":"kg"},
      ["Africa"], [{"lat":-1.3,"lng":36.8,"label":"Kenya"}],
      ["Can deliver kicks with a force equivalent to 5-6 times their body weight.","Name may come from the quill feathers resembling 19th-century secretaries' pens.","Featured on the coat of arms of Sudan and South Africa.","They mate for life and perform elaborate aerial courtship displays.","Can stamp a snake to death in just 15 seconds."],
      "https://en.wikipedia.org/wiki/Secretarybird", "Kenya", "🦅", "🇰🇪", "Africa", "Bird", "~6,700-67,000"),

    a(83, "african-elephant", "African Elephant", "Loxodonta africana",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Proboscidea","family":"Elephantidae","genus":"Loxodonta"},
      "EN", "The largest living land animal, playing a crucial role as ecosystem engineers across Africa.",
      ["savanna","forest","grassland","wetland"], "Herbivore",
      {"min":50,"max":70,"unit":"years"}, {"min":3000,"max":6000,"unit":"kg"},
      ["Africa"], [{"lat":-3.4,"lng":36.7,"label":"Tanzania"}],
      ["The largest living land animal, weighing up to 6 tonnes.","Can communicate using infrasound over distances of 10 km.","Their trunks contain over 40,000 muscles.","Elephants mourn their dead and show empathy.","Pregnancy lasts 22 months — the longest of any land animal."],
      "https://en.wikipedia.org/wiki/African_elephant", "Tanzania", "🐘", "🇹🇿", "Africa", "Mammal", "~415,000"),

    a(84, "cheetah", "Cheetah", "Acinonyx jubatus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Acinonyx"},
      "VU", "The fastest land animal on Earth, capable of reaching speeds over 100 km/h in short bursts.",
      ["savanna","grassland","open woodland"], "Carnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":20,"max":72,"unit":"kg"},
      ["Africa"], [{"lat":-22.6,"lng":17.1,"label":"Namibia"}],
      ["Fastest land animal — can reach 112 km/h in short bursts.","Can accelerate from 0 to 100 km/h in just 3 seconds.","Non-retractable claws act like running spikes for traction.","Unlike other big cats, cheetahs cannot roar but purr loudly.","Namibia has the largest free-roaming cheetah population in the world."],
      "https://en.wikipedia.org/wiki/Cheetah", "Namibia", "🐆", "🇳🇦", "Africa", "Mammal", "~6,500-7,100"),

    a(85, "spotted-hyena", "Spotted Hyena", "Crocuta crocuta",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Hyaenidae","genus":"Crocuta"},
      "LC", "Africa's most successful large predator with the strongest bite force proportionate to body size among mammals.",
      ["savanna","grassland","woodland"], "Carnivore",
      {"min":12,"max":25,"unit":"years"}, {"min":40,"max":80,"unit":"kg"},
      ["Africa"], [{"lat":-3.4,"lng":36.7,"label":"Tanzania"}],
      ["Have the strongest bite force of any land mammal relative to body size.","Females are larger and more aggressive than males, dominating the clan.","Clans can number over 80 individuals with complex social hierarchies.","More closely related to cats than dogs.","Their famous 'laugh' actually signals nervousness or submission."],
      "https://en.wikipedia.org/wiki/Spotted_hyena", "Tanzania", "🦴", "🇹🇿", "Africa", "Mammal", "~27,000-47,000"),

    a(86, "nile-monitor", "Nile Monitor", "Varanus niloticus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Varanidae","genus":"Varanus"},
      "LC", "Africa's largest lizard, an opportunistic predator found near water bodies across sub-Saharan Africa.",
      ["riverbanks","swamps","forest edges"], "Carnivore",
      {"min":10,"max":20,"unit":"years"}, {"min":5,"max":20,"unit":"kg"},
      ["Africa"], [{"lat":-1.3,"lng":36.8,"label":"Kenya"}],
      ["Second largest lizard in Africa after the Nile crocodile.","Can stay underwater for over an hour.","Excellent climbers often found in trees near rivers.","Have forked tongues like snakes to detect prey.","Invasive in Florida, USA where they are an established exotic species."],
      "https://en.wikipedia.org/wiki/Nile_monitor", "Kenya", "🦎", "🇰🇪", "Africa", "Reptile", "Unknown (common and widespread)"),

    a(87, "african-wildcat", "African Wildcat", "Felis lybica",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Felis"},
      "LC", "The wild ancestor of the domestic cat, found across Africa and parts of the Middle East.",
      ["savanna","forest","scrubland","desert edge"], "Carnivore",
      {"min":10,"max":14,"unit":"years"}, {"min":3,"max":6.5,"unit":"kg"},
      ["Africa"], [{"lat":33.6,"lng":-7.6,"label":"Morocco"}],
      ["The direct ancestor of all domestic cats worldwide.","Can interbreed with domestic cats — hybridization is a conservation threat.","Have tabby-like markings — the same pattern seen in domestic cats.","Hunt mainly at dawn and dusk, alone.","One of the most widespread small wild cat species."],
      "https://en.wikipedia.org/wiki/African_wildcat", "Morocco", "🐱", "🇲🇦", "Africa", "Mammal", "Unknown (widespread)"),

    a(88, "dugong", "Dugong", "Dugong dugon",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Sirenia","family":"Dugongidae","genus":"Dugong"},
      "VU", "The only strictly herbivorous marine mammal, grazing on seagrass meadows in warm coastal waters.",
      ["shallow coastal waters","seagrass meadows"], "Herbivore",
      {"min":50,"max":70,"unit":"years"}, {"min":200,"max":420,"unit":"kg"},
      ["Africa"], [{"lat":-25.9,"lng":32.6,"label":"Mozambique"}],
      ["The only strictly herbivorous marine mammal in existence.","Closely related to manatees — together they make up the order Sirenia.","May have inspired ancient mermaid legends.","Can hold their breath for up to 6 minutes while feeding on seagrass.","Slow reproduction rate — one calf every 2.5 to 7 years."],
      "https://en.wikipedia.org/wiki/Dugong", "Mozambique", "🐋", "🇲🇿", "Africa", "Mammal", "~30,000"),

    a(89, "mountain-zebra", "Mountain Zebra", "Equus zebra",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Perissodactyla","family":"Equidae","genus":"Equus"},
      "VU", "A zebra species adapted to mountainous terrain, found in southern Africa.",
      ["mountain slopes","arid grassland"], "Herbivore",
      {"min":15,"max":20,"unit":"years"}, {"min":240,"max":430,"unit":"kg"},
      ["Africa"], [{"lat":-32.3,"lng":19.0,"label":"South Africa"}],
      ["Each zebra has a unique stripe pattern, like human fingerprints.","No two mountain zebras have the same stripe pattern.","Their stripes may help confuse biting flies.","The Cape mountain zebra subspecies was saved from near extinction (fewer than 80 left in the 1950s).","Mountain zebras have hard, pointed hooves adapted for rocky terrain."],
      "https://en.wikipedia.org/wiki/Mountain_zebra", "South Africa", "🦓", "🇿🇦", "Africa", "Mammal", "~35,000"),

    # ASIA (90-107)
    a(90, "gharial", "Gharial", "Gavialis gangeticus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Crocodilia","family":"Gavialidae","genus":"Gavialis"},
      "CR", "A critically endangered fish-eating crocodilian with a distinctive long, narrow snout.",
      ["rivers","freshwater systems"], "Carnivore",
      {"min":30,"max":50,"unit":"years"}, {"min":150,"max":250,"unit":"kg"},
      ["Asia"], [{"lat":25.3,"lng":82.0,"label":"India"}],
      ["The most aquatic of all crocodilians — rarely leave the water.","Their long, thin snout is perfectly adapted for catching fish.","Males develop a bulbous growth on the tip of their snout called a 'ghara'.","Once found across South and Southeast Asia — now restricted to a few river systems.","Fewer than 1,000 adults remain in the wild."],
      "https://en.wikipedia.org/wiki/Gharial", "India", "🐊", "🇮🇳", "Asia", "Reptile", "~650-900"),

    a(91, "binturong", "Binturong", "Arctictis binturong",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Viverridae","genus":"Arctictis"},
      "VU", "A large, arboreal mammal of Southeast Asia, also known as the bearcat.",
      ["tropical evergreen forest"], "Omnivore",
      {"min":18,"max":25,"unit":"years"}, {"min":9,"max":20,"unit":"kg"},
      ["Asia"], [{"lat":25.3,"lng":82.0,"label":"India"}],
      ["One of only two carnivores with a prehensile tail.","Smells like buttered popcorn due to a scent gland secretion.","Key seed disperser for the strangler fig tree.","Can rotate their ankles 180 degrees for climbing down head-first.","Neither a bear nor a cat — they belong to the civet family."],
      "https://en.wikipedia.org/wiki/Binturong", "India", "🐱", "🇮🇳", "Asia", "Mammal", "Unknown (declining)"),

    a(92, "dhole", "Dhole", "Cuon alpinus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Canidae","genus":"Cuon"},
      "EN", "A highly social wild dog species from Asia, known for cooperative hunting strategies.",
      ["forest","grassland","alpine regions"], "Carnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":10,"max":20,"unit":"kg"},
      ["Asia"], [{"lat":25.3,"lng":82.0,"label":"India"}],
      ["Can take down prey 10 times their own size through teamwork.","Have fewer teeth than other canids — only 40 instead of 42.","Their whistling calls gave them the nickname 'whistling hunter'.","Pack sizes can exceed 40 individuals.","Rudyard Kipling featured dholes in 'The Second Jungle Book'."],
      "https://en.wikipedia.org/wiki/Dhole", "India", "🐕", "🇮🇳", "Asia", "Mammal", "~2,500-9,500"),

    a(93, "red-crowned-crane", "Red-crowned Crane", "Grus japonensis",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Gruiformes","family":"Gruidae","genus":"Grus"},
      "EN", "One of the world's largest and most elegant cranes, a powerful symbol of longevity in East Asia.",
      ["wetlands","marshes","rice paddies"], "Omnivore",
      {"min":30,"max":40,"unit":"years"}, {"min":7.5,"max":10.5,"unit":"kg"},
      ["Asia"], [{"lat":43.1,"lng":141.3,"label":"Japan"}],
      ["The second rarest crane species in the world.","Symbolize longevity and fidelity in Japanese and Chinese culture.","Their elaborate courtship dance involves bowing, leaping, and tossing grass.","Can fly at speeds of up to 80 km/h.","Hokkaido, Japan hosts the only non-migratory population."],
      "https://en.wikipedia.org/wiki/Red-crowned_crane", "Japan", "🦩", "🇯🇵", "Asia", "Bird", "~2,750-3,000"),

    a(94, "chinese-giant-salamander", "Chinese Giant Salamander", "Andrias davidianus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Cryptobranchidae","genus":"Andrias"},
      "CR", "The largest amphibian in the world, known as a 'living fossil' found in Chinese mountain streams.",
      ["mountain streams","rivers","rocky crevices"], "Carnivore",
      {"min":30,"max":55,"unit":"years"}, {"min":25,"max":50,"unit":"kg"},
      ["Asia"], [{"lat":30.6,"lng":104.1,"label":"China"}],
      ["The largest amphibian in the world, reaching up to 1.8 meters long.","A living fossil — unchanged for over 170 million years.","Can breathe through their wrinkled skin.","Their cries are said to resemble a crying baby — hence the Chinese name 'baby fish'.","Critically endangered due to habitat loss and over-harvesting for traditional medicine."],
      "https://en.wikipedia.org/wiki/Chinese_giant_salamander", "China", "🦎", "🇨🇳", "Asia", "Amphibian", "Unknown (severely depleted)"),

    a(95, "green-peafowl", "Green Peafowl", "Pavo muticus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Galliformes","family":"Phasianidae","genus":"Pavo"},
      "EN", "A spectacular large pheasant with iridescent green plumage, native to Southeast Asian forests.",
      ["tropical forest","open woodland","riverine forest"], "Omnivore",
      {"min":15,"max":20,"unit":"years"}, {"min":3,"max":5,"unit":"kg"},
      ["Asia"], [{"lat":19.8,"lng":96.2,"label":"Myanmar"}],
      ["Unlike Indian peafowl, both males and females have long tail feathers in the green species.","Their train feathers can spread into a fan over 1.5 meters wide.","Have been depicted in ancient Burmese and Khmer art for centuries.","Capable of short bursts of flight despite their elaborate plumage.","Considered the national bird of Myanmar."],
      "https://en.wikipedia.org/wiki/Green_peafowl", "Myanmar", "🦚", "🇲🇲", "Asia", "Bird", "~15,000-30,000"),

    a(96, "malayan-sun-bear", "Malayan Sun Bear", "Helarctos malayanus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Ursidae","genus":"Helarctos"},
      "VU", "The smallest bear species in the world, named for the distinctive golden crescent on its chest.",
      ["tropical evergreen forest","secondary forest"], "Omnivore",
      {"min":15,"max":25,"unit":"years"}, {"min":25,"max":65,"unit":"kg"},
      ["Asia"], [{"lat":4.2,"lng":101.9,"label":"Malaysia"}],
      ["The smallest bear species — only about half the size of a black bear.","Their exceptionally long tongue (up to 25 cm) is perfect for extracting honey and insects.","Extremely good climbers with large curved claws.","The golden chest mark is unique to each individual, like a fingerprint.","Can break open termite mounds and bee nests with ease."],
      "https://en.wikipedia.org/wiki/Sun_bear", "Malaysia", "🐻", "🇲🇾", "Asia", "Mammal", "Unknown (declining)"),

    a(97, "indian-rhinoceros", "Indian Rhinoceros", "Rhinoceros unicornis",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Perissodactyla","family":"Rhinocerotidae","genus":"Rhinoceros"},
      "VU", "Also called the greater one-horned rhino, the largest rhino species in Asia.",
      ["tall grassland","riverine forest","swamp"], "Herbivore",
      {"min":35,"max":45,"unit":"years"}, {"min":1500,"max":2500,"unit":"kg"},
      ["Asia"], [{"lat":26.7,"lng":93.6,"label":"India"}],
      ["The largest rhino species in Asia, weighing up to 2.5 tonnes.","Despite weighing tonnes, can run at speeds up to 40 km/h.","A single horn made of keratin — the same material as human fingernails.","One of the greatest conservation success stories — from ~200 to over 4,000 today.","Can swim and cross rivers with ease."],
      "https://en.wikipedia.org/wiki/Indian_rhinoceros", "India", "🦏", "🇮🇳", "Asia", "Mammal", "~4,000-4,500"),

    a(98, "takin", "Takin", "Budorcas taxicolor",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Bovidae","genus":"Budorcas"},
      "VU", "A large, muscular goat-antelope found in the eastern Himalayas, Bhutan's national animal.",
      ["alpine meadow","subalpine forest","rocky slopes"], "Herbivore",
      {"min":12,"max":16,"unit":"years"}, {"min":250,"max":400,"unit":"kg"},
      ["Asia"], [{"lat":27.5,"lng":90.4,"label":"Bhutan"}],
      ["Bhutan's national animal, chosen for its mythical appearance.","Legend says takin were created from the remains of a goat eaten by a saint.","They secrete an oily substance through their skin that acts as a natural raincoat.","Despite their bulky appearance, they are incredibly agile on steep terrain.","Males use their massive horns in dramatic head-butting contests."],
      "https://en.wikipedia.org/wiki/Takin", "Bhutan", "🐐", "🇧🇹", "Asia", "Mammal", "Unknown (~10,000-15,000)"),

    a(99, "crimson-sunbird", "Crimson Sunbird", "Aethopyga siparaja",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Passeriformes","family":"Nectariniidae","genus":"Aethopyga"},
      "LC", "A tiny, brilliantly colored nectar-feeding bird, the national bird of Singapore.",
      ["tropical forest","gardens","plantation"], "Omnivore",
      {"min":5,"max":8,"unit":"years"}, {"min":0.006,"max":0.012,"unit":"kg"},
      ["Asia"], [{"lat":-6.2,"lng":106.8,"label":"Indonesia"}],
      ["Males display brilliant crimson plumage during breeding season.","Hover at flowers like hummingbirds to feed on nectar.","Can be found from India to Indonesia across a huge range.","Their long, curved bills are perfectly adapted for probing flowers.","Singapore named it the unofficial national bird in 2015."],
      "https://en.wikipedia.org/wiki/Crimson_sunbird", "Indonesia", "🐦", "🇮🇩", "Asia", "Bird", "Unknown (common)"),

    a(100, "chinese-pangolin", "Chinese Pangolin", "Manis pentadactyla",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Pholidota","family":"Manidae","genus":"Manis"},
      "CR", "A scaly anteater heavily trafficked for traditional medicine, now one of the most endangered mammals in Asia.",
      ["forest","grassland","agricultural land"], "Carnivore",
      {"min":12,"max":20,"unit":"years"}, {"min":2,"max":7,"unit":"kg"},
      ["Asia"], [{"lat":30.6,"lng":104.1,"label":"China"}],
      ["Pangolin scales are made of keratin — the same as human nails.","They consume up to 70 million insects per year, controlling pest populations.","When threatened, they roll into a tight armored ball.","Can climb trees and dig burrows with equal skill.","The world's most trafficked mammal, with over 1 million poached in the last decade."],
      "https://en.wikipedia.org/wiki/Chinese_pangolin", "China", "🦎", "🇨🇳", "Asia", "Mammal", "~50,000 (declining rapidly)"),

    a(101, "asian-water-buffalo", "Asian Water Buffalo", "Bubalus bubalis",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Bovidae","genus":"Bubalus"},
      "EN", "A massive bovine species well-adapted to wetland habitats, ancestor of the domestic water buffalo.",
      ["swamp","tall grassland","riverine forest"], "Herbivore",
      {"min":20,"max":25,"unit":"years"}, {"min":700,"max":1200,"unit":"kg"},
      ["Asia"], [{"lat":14.9,"lng":102.0,"label":"Thailand"}],
      ["Wild populations are endangered while domesticated ones number over 200 million.","Their wide-splayed hooves prevent them from sinking in mud.","Can be domesticated and have been used for agriculture for over 5,000 years.","A single wild population of fewer than 3,500 remains in Thailand.","Their horns can span over 2 meters across."],
      "https://en.wikipedia.org/wiki/Water_buffalo", "Thailand", "🐃", "🇹🇭", "Asia", "Mammal", "~3,400 (wild)"),

    a(102, "mekong-giant-catfish", "Mekong Giant Catfish", "Pangasianodon gigas",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Siluriformes","family":"Pangasiidae","genus":"Pangasianodon"},
      "CR", "One of the largest freshwater fish in the world, endemic to the Mekong River basin.",
      ["large rivers"], "Herbivore",
      {"min":20,"max":30,"unit":"years"}, {"min":100,"max":350,"unit":"kg"},
      ["Asia"], [{"lat":18.8,"lng":98.9,"label":"Thailand"}],
      ["Can grow up to 3 meters long and weigh over 300 kg.","One of the largest freshwater fish species in the world.","Considered sacred in Buddhist tradition — releasing them earns merit.","Adults are toothless, feeding entirely on algae and plants.","Population has declined over 80% in the last 20 years."],
      "https://en.wikipedia.org/wiki/Mekong_giant_catfish", "Thailand", "🐟", "🇹🇭", "Asia", "Fish", "~200-300"),

    a(103, "japanese-giant-hornet", "Asian Giant Hornet", "Vespa mandarinia",
      {"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Hymenoptera","family":"Vespidae","genus":"Vespa"},
      "LC", "The world's largest hornet with a powerful venomous sting, native to East Asia.",
      ["temperate forest","mountain forest"], "Carnivore",
      {"min":1,"max":2,"unit":"years"}, {"min":0.006,"max":0.02,"unit":"kg"},
      ["Asia"], [{"lat":36.2,"lng":138.3,"label":"Japan"}],
      ["The world's largest hornet, with a wingspan of up to 7.5 cm.","Their venom contains a neurotoxin that can dissolve human tissue.","A small group can massacre an entire honeybee colony in hours.","In Japan, they cause 30-50 human deaths per year.","Can fly up to 100 km per day at speeds of 40 km/h."],
      "https://en.wikipedia.org/wiki/Asian_giant_hornet", "Japan", "🐝", "🇯🇵", "Asia", "Insect", "Unknown (common)"),

    a(104, "nicobar-pigeon", "Nicobar Pigeon", "Caloenas nicobarica",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Columbiformes","family":"Columbidae","genus":"Caloenas"},
      "NT", "A stunning metallic-green pigeon, the closest living relative to the extinct dodo.",
      ["tropical forest","coastal forest","islands"], "Herbivore",
      {"min":10,"max":15,"unit":"years"}, {"min":0.5,"max":1,"unit":"kg"},
      ["Asia"], [{"lat":7.0,"lng":93.8,"label":"India"}],
      ["The closest living relative of the extinct dodo bird.","Their iridescent plumage shimmers in green, copper, and blue.","Found only on small islands in Southeast Asia and the Indian Ocean.","Unlike most pigeons, they prefer dense forest and avoid human settlements.","Males perform courtship displays with bowing and cooing."],
      "https://en.wikipedia.org/wiki/Nicobar_pigeon", "India", "🕊️", "🇮🇳", "Asia", "Bird", "Unknown (~10,000 adults)"),

    a(105, "indochinese-tiger", "Indochinese Tiger", "Panthera tigris tigris",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Panthera"},
      "EN", "A tiger subspecies found in Southeast Asia, critically threatened by habitat loss and poaching.",
      ["tropical forest","montane forest","grassland"], "Carnivore",
      {"min":15,"max":20,"unit":"years"}, {"min":150,"max":250,"unit":"kg"},
      ["Asia"], [{"lat":14.9,"lng":102.0,"label":"Thailand"}],
      ["Fewer than 250 mature individuals remain in the wild.","Each tiger has a unique stripe pattern — no two are alike.","They are solitary and territorial, requiring large home ranges.","Tigers are apex predators essential for maintaining ecosystem balance.","Can eat up to 40 kg of meat in a single sitting."],
      "https://en.wikipedia.org/wiki/Indochinese_tiger", "Thailand", "🐯", "🇹🇭", "Asia", "Mammal", "~250 (wild)"),

    a(106, "western-hoolock-gibbon", "Western Hoolock Gibbon", "Hoolock hoolock",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Hylobatidae","genus":"Hoolock"},
      "EN", "India's only ape species, an acrobatic brachiator found in Northeast India's forests.",
      ["tropical evergreen forest","semi-evergreen forest"], "Omnivore",
      {"min":20,"max":30,"unit":"years"}, {"min":6,"max":9,"unit":"kg"},
      ["Asia"], [{"lat":26.1,"lng":93.7,"label":"India"}],
      ["India's only ape species — all other primates in India are monkeys.","They are brachiators, swinging through trees using only their arms.","Mated pairs sing elaborate duets every morning to mark their territory.","Females are distinguished by their white eyebrows.","Can leap over 10 meters between trees."],
      "https://en.wikipedia.org/wiki/Western_hoolock_gibbon", "India", "🐒", "🇮🇳", "Asia", "Mammal", "~2,600"),

    a(107, "sambar-deer", "Sambar Deer", "Rusa unicolor",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Cervidae","genus":"Rusa"},
      "VU", "One of the largest deer species in the world, found across South and Southeast Asia.",
      ["tropical forest","deciduous forest","grassland"], "Herbivore",
      {"min":15,"max":20,"unit":"years"}, {"min":180,"max":320,"unit":"kg"},
      ["Asia"], [{"lat":25.3,"lng":82.0,"label":"India"}],
      ["One of the largest deer species, with males standing up to 160 cm at the shoulder.","Only the males have antlers, which can grow up to 1 meter long.","They are primarily nocturnal, feeding mostly at night.","Their alarm call — a loud, repetitive honk — alerts all nearby animals to danger.","A key prey species for tigers and leopards across their range."],
      "https://en.wikipedia.org/wiki/Sambar_deer", "India", "🦌", "🇮🇳", "Asia", "Mammal", "Unknown (widespread)"),

    # EUROPE (108-119)
    a(108, "eurasian-lynx", "Eurasian Lynx", "Lynx lynx",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Lynx"},
      "NT", "Europe's third largest predator, recognizable by its distinctive ear tufts and piercing eyes.",
      ["boreal forest","temperate forest","mountain forest"], "Carnivore",
      {"min":12,"max":17,"unit":"years"}, {"min":15,"max":30,"unit":"kg"},
      ["Europe"], [{"lat":61.5,"lng":24.0,"label":"Finland"}],
      ["Europe's third largest predator after the brown bear and wolf.","Their ear tufts act like antennas to detect faint sounds.","Can take down prey four times their own size — including deer.","Padded paws allow them to walk silently like ghost cats.","Have been successfully reintroduced to several European countries."],
      "https://en.wikipedia.org/wiki/Eurasian_lynx", "Finland", "🐱", "🇫🇮", "Europe", "Mammal", "~45,000"),

    a(109, "european-otter", "Eurasian Otter", "Lutra lutra",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Lutra"},
      "NT", "A semi-aquatic mammal found in freshwater and coastal habitats across Europe and Asia.",
      ["rivers","lakes","coastal areas"], "Carnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":6,"max":11,"unit":"kg"},
      ["Europe"], [{"lat":56.8,"lng":-5.1,"label":"Scotland"}],
      ["Their fur is so dense they have over 100,000 hairs per square cm.","Can close their nostrils and ears when diving underwater.","Hold hands while sleeping so they don't drift apart — well, sea otters do.","Have a third translucent eyelid for underwater vision.","Recovered significantly in the UK after near-extinction from pesticides."],
      "https://en.wikipedia.org/wiki/Eurasian_otter", "Scotland", "🦦", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Europe", "Mammal", "~200,000"),

    a(110, "european-badger", "European Badger", "Meles meles",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Meles"},
      "LC", "A sturdy, social mammal known for its distinctive black and white facial markings and complex underground setts.",
      ["woodland","grassland","hedgerows"], "Omnivore",
      {"min":10,"max":15,"unit":"years"}, {"min":8,"max":17,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":-0.1,"label":"England"}],
      ["Their underground homes (setts) can be over 100 years old with extensive tunnel systems.","Live in social groups called 'clans' of up to 12 individuals.","Their distinctive facial markings are unique to each individual.","Can dig through soil at remarkable speed using powerful front claws.","Badgers are one of Britain's oldest native mammals, present for over 500,000 years."],
      "https://en.wikipedia.org/wiki/European_badger", "England", "🦡", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Europe", "Mammal", "~500,000"),

    a(111, "fire-salamander", "Fire Salamander", "Salamandra salamandra",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Salamandridae","genus":"Salamandra"},
      "LC", "Europe's most iconic amphibian, recognized by its vivid black and yellow warning coloration.",
      ["deciduous forest","coniferous forest","moist woodland"], "Carnivore",
      {"min":15,"max":25,"unit":"years"}, {"min":0.02,"max":0.04,"unit":"kg"},
      ["Europe"], [{"lat":51.2,"lng":10.5,"label":"Germany"}],
      ["Their bright yellow-black pattern warns predators of toxic skin secretions.","Can live up to 25 years — among the longest-lived amphibians.","Some populations give birth to fully metamorphosed young instead of larvae.","One of few amphibians active in cold winter conditions.","Named after the belief they were born in fire — a myth from the Middle Ages."],
      "https://en.wikipedia.org/wiki/Fire_salamander", "Germany", "🦎", "🇩🇪", "Europe", "Amphibian", "Unknown (widespread)"),

    a(112, "european-robin", "European Robin", "Erithacus rubecula",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Passeriformes","family":"Muscicapidae","genus":"Erithacus"},
      "LC", "Britain's beloved national bird, recognized by its warm orange breast and melodious song.",
      ["woodland","gardens","hedgerows","parks"], "Omnivore",
      {"min":2,"max":5,"unit":"years"}, {"min":0.016,"max":0.022,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":-0.1,"label":"England"}],
      ["Britain's unofficial national bird since the 1960s.","Extremely territorial — males will fight to the death to defend their patch.","They are one of the few birds that sing year-round, even at night under streetlights.","Their distinctive red breast is actually orange — named 'red' before the word 'orange' existed in English.","Follow gardeners to catch insects disturbed by digging."],
      "https://en.wikipedia.org/wiki/European_robin", "England", "🐦", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Europe", "Bird", "~75,000,000 pairs (Europe)"),

    a(113, "pine-marten", "Pine Marten", "Martes martes",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Martes"},
      "LC", "An agile arboreal predator of European forests, once nearly extinct in Britain.",
      ["coniferous forest","mixed woodland","scattered woodland"], "Carnivore",
      {"min":8,"max":12,"unit":"years"}, {"min":1,"max":2.2,"unit":"kg"},
      ["Europe"], [{"lat":56.8,"lng":-5.1,"label":"Scotland"}],
      ["They are helping control invasive grey squirrel populations by outcompeting them.","Pine martens are cat-sized but belong to the weasel family.","Almost completely extinct in England by the early 20th century — now recovering.","Excellent climbers that hunt both in trees and on the ground.","Their fur was once so valuable it was used as currency in parts of Russia."],
      "https://en.wikipedia.org/wiki/Pine_marten", "Scotland", "🐱", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Europe", "Mammal", "~400,000"),

    a(114, "wolverine", "Wolverine", "Gulo gulo",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Gulo"},
      "VU", "The largest terrestrial member of the weasel family, known for extraordinary strength and ferocity.",
      ["arctic tundra","boreal forest","alpine regions"], "Carnivore",
      {"min":8,"max":13,"unit":"years"}, {"min":10,"max":25,"unit":"kg"},
      ["Europe"], [{"lat":62.5,"lng":9.4,"label":"Norway"}],
      ["Can take down prey 10 times their size — including caribou and moose.","Their powerful jaws can crack frozen bones and crush thick femurs.","Scandinavian populations are the southernmost remaining in Europe.","Wolverines have been documented traveling over 30 km in a single day.","Their dense frost-resistant fur was traditionally used by trappers for parka ruffs."],
      "https://en.wikipedia.org/wiki/Wolverine", "Norway", "🦡", "🇳🇴", "Europe", "Mammal", "~700 (Scandinavia)"),

    a(115, "european-mole", "European Mole", "Talpa europaea",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Eulipotyphla","family":"Talpidae","genus":"Talpa"},
      "LC", "A subterranean mammal adapted to a life underground, found across Europe.",
      ["grassland","arable land","deciduous woodland","gardens"], "Carnivore",
      {"min":3,"max":6,"unit":"years"}, {"min":0.06,"max":0.12,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":-0.1,"label":"England"}],
      ["Can dig up to 20 meters of tunnel per day.","Their star-shaped nose has over 25,000 touch receptors.","Nearly blind but detect prey through vibration and smell.","Can tolerate low oxygen levels that would suffocate most mammals.","A single molehill can displace over 100 kg of soil."],
      "https://en.wikipedia.org/wiki/European_mole", "England", "🐹", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Europe", "Mammal", "~31,000,000"),

    a(116, "red-deer", "Red Deer", "Cervus elaphus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Cervidae","genus":"Cervus"},
      "LC", "One of the largest deer species, an iconic symbol of the Scottish Highlands.",
      ["forest","moorland","mountain slopes"], "Herbivore",
      {"min":15,"max":20,"unit":"years"}, {"min":120,"max":240,"unit":"kg"},
      ["Europe"], [{"lat":56.8,"lng":-5.1,"label":"Scotland"}],
      ["The fourth largest deer species in the world.","Only males grow antlers, which can have up to 16 points.","Stags can be heard roaring during the autumn rut for kilometers.","A single red deer can produce up to 3 kg of antler velvet annually.","Monarch of the Glen — Scotland's most iconic wildlife image."],
      "https://en.wikipedia.org/wiki/Red_deer", "Scotland", "🦌", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "Europe", "Mammal", "~2,000,000 (Europe)"),

    a(117, "european-hedgehog", "European Hedgehog", "Erinaceus europaeus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Eulipotyphla","family":"Erinaceidae","genus":"Erinaceus"},
      "LC", "A familiar garden visitor covered in spines, beloved across Europe but in significant decline.",
      ["hedgerows","woodland edge","gardens","grassland"], "Omnivore",
      {"min":3,"max":7,"unit":"years"}, {"min":0.5,"max":1.1,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":-0.1,"label":"England"}],
      ["Covered in around 5,000-7,000 spines made of keratin.","When threatened, they roll into a tight ball of spikes.","UK hedgehog populations have declined by over 50% since 2000.","They can travel up to 3 km per night searching for food.","Hedgehogs are surprisingly good swimmers."],
      "https://en.wikipedia.org/wiki/Western_European_hedgehog", "England", "🦔", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Europe", "Mammal", "Unknown (declining)"),

    a(118, "white-stork", "White Stork", "Ciconia ciconia",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Ciconiiformes","family":"Ciconiidae","genus":"Ciconia"},
      "LC", "A large, migratory wading bird famous for returning to the same nest year after year.",
      ["wetlands","grassland","farmland"], "Carnivore",
      {"min":20,"max":30,"unit":"years"}, {"min":2.2,"max":4.5,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":21.0,"label":"Poland"}],
      ["In Polish folklore, storks bring babies to families.","Their nests can weigh over 500 kg — some are reused for centuries.","They migrate between Europe and Africa, covering 10,000+ km each way.","Can be seen standing on one leg — scientists still debate why.","Poland hosts the largest white stork population in the world."],
      "https://en.wikipedia.org/wiki/White_stork", "Poland", "🦩", "🇵🇱", "Europe", "Bird", "~300,000 pairs"),

    a(119, "common-kingfisher", "Common Kingfisher", "Alcedo atthis",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Coraciiformes","family":"Alcedinidae","genus":"Alcedo"},
      "LC", "A dazzling flash of electric blue and orange along European waterways.",
      ["rivers","streams","lakes","ponds"], "Carnivore",
      {"min":5,"max":7,"unit":"years"}, {"min":0.034,"max":0.046,"unit":"kg"},
      ["Europe"], [{"lat":52.2,"lng":-0.1,"label":"England"}],
      ["Their iridescent blue plumage is not from pigment but light refraction on feather structure.","Can dive into water at speeds up to 25 km/h to catch fish.","Must eat roughly their body weight in fish every day to survive.","Kingfishers have a specialized third eyelid that acts as swimming goggles.","Despite their vivid colors, they are surprisingly hard to spot due to their speed."],
      "https://en.wikipedia.org/wiki/Common_kingfisher", "England", "🐦", "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "Europe", "Bird", "~700,000 pairs (Europe)"),

    # NORTH AMERICA (120-131)
    a(120, "gray-wolf", "Gray Wolf", "Canis lupus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Canidae","genus":"Canis"},
      "LC", "The largest wild member of the canid family, a keystone predator of North American ecosystems.",
      ["forest","tundra","grassland","mountain"], "Carnivore",
      {"min":6,"max":13,"unit":"years"}, {"min":25,"max":80,"unit":"kg"},
      ["North America"], [{"lat":44.7,"lng":-110.5,"label":"Yellowstone"}],
      ["Yellowstone's wolf reintroduction in 1995 changed the entire ecosystem.","Can travel over 50 km in a single day while hunting.","A pack howl can be heard from over 16 km away.","Wolf packs have complex social hierarchies with alpha and beta roles.","Their reintroduction to Yellowstone even changed how rivers flow (trophic cascade)."],
      "https://en.wikipedia.org/wiki/Gray_wolf", "Yellowstone", "🐺", "🇺🇸", "North America", "Mammal", "~500,000"),

    a(121, "american-bison", "American Bison", "Bison bison",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Bovidae","genus":"Bison"},
      "NT", "North America's largest land animal, a symbol of the American West and conservation success.",
      ["grassland","prairie","forest clearings"], "Herbivore",
      {"min":15,"max":20,"unit":"years"}, {"min":400,"max":900,"unit":"kg"},
      ["North America"], [{"lat":44.7,"lng":-110.5,"label":"Yellowstone"}],
      ["Once numbered 30-60 million — reduced to fewer than 1,000 by 1890.","Can run at speeds up to 55 km/h despite weighing nearly a tonne.","Yellowstone has the only continuously wild, free-roaming bison herd in the US.","Their massive heads act as snowplows to find food in winter.","Bison can pivot on both front and rear hooves — horses can only do the front."],
      "https://en.wikipedia.org/wiki/American_bison", "Yellowstone", "🦬", "🇺🇸", "North America", "Mammal", "~31,000 (wild)"),

    a(122, "moose", "Moose", "Alces alces",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Cervidae","genus":"Alces"},
      "LC", "The largest member of the deer family, found across Canada's vast boreal forests.",
      ["boreal forest","temperate forest","wetland"], "Herbivore",
      {"min":15,"max":25,"unit":"years"}, {"min":300,"max":700,"unit":"kg"},
      ["North America"], [{"lat":56.1,"lng":-106.3,"label":"Canada"}],
      ["The largest deer species — males can stand over 2 meters at the shoulder.","Their antlers can span up to 2 meters across and weigh 20 kg.","Despite their size, moose are excellent swimmers — can dive 5 meters deep.","Moose are responsible for more human injuries than bears in North America.","Can eat up to 25 kg of vegetation per day."],
      "https://en.wikipedia.org/wiki/Moose", "Canada", "🦌", "🇨🇦", "North America", "Mammal", "~500,000-1,000,000"),

    a(123, "mountain-goat", "Mountain Goat", "Oreamnos americanus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Bovidae","genus":"Oreamnos"},
      "LC", "A superbly adapted alpine climber found in the rugged mountains of western North America.",
      ["alpine tundra","rocky cliffs","mountain slopes"], "Herbivore",
      {"min":12,"max":18,"unit":"years"}, {"min":60,"max":140,"unit":"kg"},
      ["North America"], [{"lat":51.2,"lng":-116.9,"label":"Canada"}],
      ["Can scale near-vertical cliff faces with specially adapted split hooves.","Their white coats provide camouflage in snowy alpine environments.","Can jump over 3 meters in a single bound.","Their thick double-layered wool undercoat keeps them warm at -40°C.","Not true goats — they are more closely related to antelopes and gazelles."],
      "https://en.wikipedia.org/wiki/Mountain_goat", "Canada", "🐐", "🇨🇦", "North America", "Mammal", "~100,000"),

    a(124, "gila-monster", "Gila Monster", "Heloderma suspectum",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Helodermatidae","genus":"Heloderma"},
      "NT", "One of only two venomous lizards in the world, native to the southwestern United States.",
      ["desert","scrubland","rocky hillsides"], "Carnivore",
      {"min":20,"max":30,"unit":"years"}, {"min":0.35,"max":2.3,"unit":"kg"},
      ["North America"], [{"lat":33.4,"lng":-112.1,"label":"Arizona"}],
      ["One of only two venomous lizard species in the world.","Their venom contains a protein (exendin-4) used in diabetes medication (Byetta).","Store fat in their tails — can survive months without eating.","Bead-like scales called osteoderms form a bony armor under their skin.","Named after the Gila River basin in Arizona and New Mexico."],
      "https://en.wikipedia.org/wiki/Gila_monster", "Arizona", "🦎", "🇺🇸", "North America", "Reptile", "Unknown (protected)"),

    a(125, "alligator-snapping-turtle", "Alligator Snapping Turtle", "Macrochelys temminckii",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Testudines","family":"Chelydridae","genus":"Macrochelys"},
      "VU", "The largest freshwater turtle in North America, known for its powerful bite and unique worm-lure hunting technique.",
      ["rivers","lakes","bayous","swamps"], "Carnivore",
      {"min":50,"max":100,"unit":"years"}, {"min":8,"max":80,"unit":"kg"},
      ["North America"], [{"lat":29.7,"lng":-83.3,"label":"Florida"}],
      ["The largest freshwater turtle in North America — can weigh over 90 kg.","They use a pink worm-like appendage on their tongue to lure fish.","Their bite force can easily snap a broomstick in half.","Can hold their breath underwater for up to 50 minutes.","Once hunted extensively for turtle soup — now protected across their range."],
      "https://en.wikipedia.org/wiki/Alligator_snapping_turtle", "Florida", "🐢", "🇺🇸", "North America", "Reptile", "~360,000 (declining)"),

    a(126, "pronghorn", "Pronghorn", "Antilocapra americana",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Antilocapridae","genus":"Antilocapra"},
      "LC", "North America's fastest land animal, the second fastest in the world after the cheetah.",
      ["grassland","prairie","semidesert"], "Herbivore",
      {"min":7,"max":12,"unit":"years"}, {"min":35,"max":65,"unit":"kg"},
      ["North America"], [{"lat":42.8,"lng":-107.6,"label":"Wyoming"}],
      ["Second fastest land animal — can sustain speeds of 65 km/h for miles.","No natural predator today can match their speed — likely evolved to outrun extinct American cheetahs.","Both males and females have horns — the only North American ungulate where this is true.","Their horn sheaths are shed and regrown annually, unique among horned animals.","Can see up to 6 km away, giving them exceptional detection of predators."],
      "https://en.wikipedia.org/wiki/Pronghorn", "Wyoming", "🦌", "🇺🇸", "North America", "Mammal", "~500,000-1,000,000"),

    a(127, "roadrunner", "Greater Roadrunner", "Geococcyx californianus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Cuculiformes","family":"Cuculidae","genus":"Geococcyx"},
      "LC", "A ground-dwelling cuckoo of the American Southwest, famous from Looney Tunes and real-life rattlesnake hunting.",
      ["desert","scrubland","grassland"], "Carnivore",
      {"min":5,"max":8,"unit":"years"}, {"min":0.2,"max":0.5,"unit":"kg"},
      ["North America"], [{"lat":33.4,"lng":-112.1,"label":"Arizona"}],
      ["Can run at speeds up to 32 km/h, making them the fastest running bird that can also fly.","Actually do hunt and eat rattlesnakes — often in pairs for safety.","Drop prey onto hard surfaces to break it open before eating.","Unlike the cartoon, roadrunners can fly short distances.","Their zygodactyl feet (two toes forward, two back) help them run at high speeds."],
      "https://en.wikipedia.org/wiki/Greater_roadrunner", "Arizona", "🐦", "🇺🇸", "North America", "Bird", "Unknown (common)"),

    a(128, "bobcat", "Bobcat", "Lynx rufus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Lynx"},
      "LC", "North America's most common wild cat, adaptable to a wide range of habitats.",
      ["forest","desert","scrubland","suburban"], "Carnivore",
      {"min":7,"max":10,"unit":"years"}, {"min":4,"max":18,"unit":"kg"},
      ["North America"], [{"lat":31.0,"lng":-97.7,"label":"Texas"}],
      ["Named for their short, bobbed tail — usually 10-15 cm long.","Can pounce from 3 meters away to catch prey.","They are found in every US state except Delaware — highly adaptable.","Have excellent night vision with reflective eyes (tapetum lucidum).","Twice the size of a domestic cat but still relatively small."],
      "https://en.wikipedia.org/wiki/Bobcat", "Texas", "🐱", "🇺🇸", "North America", "Mammal", "~3,500,000"),

    a(129, "west-indian-manatee", "West Indian Manatee", "Trichechus manatus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Sirenia","family":"Trichechidae","genus":"Trichechus"},
      "VU", "A gentle, slow-moving marine mammal also known as the sea cow, found in Florida's warm coastal waters.",
      ["coastal waters","rivers","estuaries","springs"], "Herbivore",
      {"min":40,"max":60,"unit":"years"}, {"min":400,"max":600,"unit":"kg"},
      ["North America"], [{"lat":27.7,"lng":-81.5,"label":"Florida"}],
      ["Often called 'sea cows' because they graze on seagrass like bovines on grass.","They have no natural predators — their main threat is boat propellers.","Can hold their breath for up to 20 minutes while resting.","A single adult can eat up to 50 kg of seagrass per day.","Florida manatee population has rebounded to over 13,000, leading to downlisting from endangered."],
      "https://en.wikipedia.org/wiki/West_Indian_manatee", "Florida", "🐋", "🇺🇸", "North America", "Mammal", "~13,000 (Florida)"),

    a(130, "california-condor", "California Condor", "Gymnogyps californianus",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Cathartiformes","family":"Cathartidae","genus":"Gymnogyps"},
      "CR", "North America's largest flying bird, saved from extinction by one of the most ambitious conservation programs ever.",
      ["rocky cliffs","grassland","forest"], "Carnivore",
      {"min":30,"max":60,"unit":"years"}, {"min":8,"max":14,"unit":"kg"},
      ["North America"], [{"lat":36.1,"lng":-119.4,"label":"California"}],
      ["The largest flying bird in North America with a wingspan up to 3 meters.","Was reduced to just 27 individuals in 1987 — all taken into captivity.","Now over 500 birds exist, with over 300 in the wild.","They can fly at altitudes of over 4,500 meters.","Condors have been known to live over 60 years in captivity."],
      "https://en.wikipedia.org/wiki/California_condor", "California", "🦩", "🇺🇸", "North America", "Bird", "~500"),

    a(131, "raccoon", "Raccoon", "Procyon lotor",
      {"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Procyonidae","genus":"Procyon"},
      "LC", "A highly intelligent and adaptable mammal recognizable by its black mask and ringed tail.",
      ["forest","urban areas","wetlands","suburban"], "Omnivore",
      {"min":2,"max":5,"unit":"years"}, {"min":5,"max":15,"unit":"kg"},
      ["North America"], [{"lat":38.9,"lng":-77.0,"label":"USA"}],
      ["Their scientific name 'lotor' means 'washer' — they often appear to wash their food.","Have incredibly dexterous front paws that can open jars, doors, and latches.","Can remember solutions to tasks for up to 3 years.","Their iconic black mask may reduce glare and help them recognize each other.","Thrive in cities — urban raccoon populations can exceed rural ones."],
      "https://en.wikipedia.org/wiki/Raccoon", "USA", "🦝", "🇺🇸", "North America", "Mammal", "~20,000,000+"),
]

def main():
    with open(DATA_PATH) as f:
        data = json.load(f)
    
    existing_ids = {item["id"] for item in data}
    new_count = 0
    for animal in animals:
        if animal["id"] not in existing_ids:
            data.append(animal)
            new_count += 1
        else:
            print(f"Skipping duplicate ID {animal['id']}")
    
    with open(DATA_PATH, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Added {new_count} new animals. Total: {len(data)}")

if __name__ == "__main__":
    main()
