# Animal data for expansion - sets N list
N = []

# AFRICA (+19)
N += [mk("african-penguin","African Penguin","Spheniscus demersus","Aves","Sphenisciformes","Spheniscidae","Spheniscus","EN","Piscivore",10,20,2,5,"Africa","South Africa",-33.92,18.42,"The African Penguin inhabits rocky coastlines of South Africa and Namibia.","🐧",["Also called jackass penguin due to braying call","Can dive to depths over 130 meters","Pink eye gland helps regulate body temperature","Pairs for life returning to same nest site","Oil spills are among their greatest threats"],"~25,000 pairs"),
mk("grevys-zebra","Grevy's Zebra","Equus grevyi","Mammalia","Perissodactyla","Equidae","Equus","EN","Herbivore",20,25,350,450,"Africa","Kenya",0.59,37.0,"Grevy's Zebra inhabits semi-arid grasslands of Kenya and Ethiopia.","🦓",["Stripes much narrower than other zebra species","Can survive up to five days without water","Fewer than 3000 remain in the wild","Ears larger and more rounded than plains zebras","Males hold large territories"],"~3,000"),
mk("okapi","Okapi","Okapia johnstoni","Mammalia","Artiodactyla","Giraffidae","Okapia","EN","Herbivore",20,30,200,350,"Africa","Congo",0.23,29.0,"The Okapi inhabits dense rainforests of the Congo Basin.","🦒",["Only living relative of the giraffe","Striped hindquarters help calves follow mothers","Prehensile tongue can wash their own eyelids","Communicate using infrasound undetectable to humans","Named after explorer Sir Harry Johnston"],"~35,000"),
mk("shoebill","Shoebill","Balaeniceps rex","Aves","Pelecaniformes","Balaenicipitidae","Balaeniceps","VU","Carnivore",30,35,4,7,"Africa","Uganda",1.37,32.29,"The Shoebill inhabits papyrus swamps of East Africa.","🦢",["Bill can measure up to 24 centimeters long","Stand motionless for hours while hunting fish","Can decapitate prey before swallowing","Clatter bills rapidly during nesting","Depicted in ancient Egyptian artwork"],"~5,000-8,000"),
mk("nile-crocodile","Nile Crocodile","Crocodylus niloticus","Reptilia","Crocodilia","Crocodylidae","Crocodylus","LC","Carnivore",50,80,200,750,"Africa","Kenya",-1.29,36.82,"The Nile Crocodile inhabits rivers and marshlands across sub-Saharan Africa.","🐊",["Strongest bite force of any living animal","Can hold breath underwater up to 2 hours at rest","Females carry hatchlings to water in mouths","Can grow up to 5 meters long","Known to take prey as large as hippos"],"~500,000"),
mk("african-grey-parrot","African Grey Parrot","Psittacus erithacus","Aves","Psittaciformes","Psittacidae","Psittacus","EN","Omnivore",40,60,0.3,0.6,"Africa","Cameroon",5.0,11.0,"The African Grey Parrot inhabits rainforests of West and Central Africa.","🦜",["Can understand concepts like color shape and number","Can learn vocabularies of over 1000 words","Cognitive abilities comparable to a 5-year-old","Wild populations declined due to pet trade","Live in large flocks highly social"],"~630,000"),
mk("mandrill","Mandrill","Mandrillus sphinx","Mammalia","Primates","Cercopithecidae","Mandrillus","VU","Omnivore",20,30,20,50,"Africa","Cameroon",4.0,13.0,"The Mandrill inhabits tropical rainforests of Central Africa.","🐵",["Most colorful face of any mammal","Color intensity indicates social rank","Troops can contain up to 1000 individuals","Cheek pouches store food equal to stomach capacity","Shy despite intimidating appearance"],"~100,000"),
mk("ground-pangolin","Ground Pangolin","Manis temminckii","Mammalia","Pholidota","Manidae","Manis","EN","Insectivore",13,20,7,18,"Africa","South Africa",-25.0,27.0,"The Ground Pangolin inhabits savannas and woodlands of sub-Saharan Africa.","🦔",["Only mammals entirely covered in keratin scales","Consume up to 70 million ants and termites per year","No teeth using muscular stomach with pebbles","Most trafficked mammals in the world","Tongue can be longer than entire body"],"~100,000"),
mk("aardvark","Aardvark","Orycteropus afer","Mammalia","Tubulidentata","Orycteropodidae","Orycteropus","LC","Insectivore",18,23,40,80,"Africa","South Africa",-29.0,24.0,"The Aardvark inhabits savannas and grasslands of sub-Saharan Africa.","🐗",["Can dig half a meter of soil in 15 seconds","Only living species in order Tubulidentata","Tongue up to 30 cm long coated in sticky saliva","Eats about 50000 termites per night","Burrows shelter warthogs and hyenas"],"~Unknown"),
mk("gelada","Gelada","Theropithecus gelada","Mammalia","Primates","Cercopithecidae","Theropithecus","EN","Herbivore",15,20,15,25,"Africa","Ethiopia",10.0,39.0,"The Gelada inhabits alpine grasslands of the Ethiopian Highlands.","🐒",["Only primates that are primarily grazers","Red chest patch indicates health and dominance","Largest primate troops can exceed 1000","Spend most time on ground of any primate except humans","Complex vocal repertoire with 30 distinct calls"],"~200,000"),
mk("caracal","Caracal","Caracal caracal","Mammalia","Carnivora","Felidae","Caracal","LC","Carnivore",12,15,8,20,"Africa","South Africa",-30.0,25.0,"The Caracal inhabits arid regions and savannas of Africa.","🦝",["Can leap up to 3 meters to catch birds in flight","Ear tufts may help detect prey sounds","Ancient Egyptians trained them for hunting","Solitary and highly territorial","Can survive without drinking water"],"~Unknown"),
mk("secretary-bird","Secretary Bird","Sagittarius serpentarius","Aves","Accipitriformes","Sagittariidae","Sagittarius","EN","Carnivore",15,20,3,5,"Africa","Kenya",-1.0,37.0,"The Secretary Bird inhabits open grasslands of sub-Saharan Africa.","🦅",["Kicks with force 5-6 times body weight","Only bird of prey that hunts primarily on foot","Scientific name means archer of snakes","Can cover 20-30 km per day walking","Name may come from quill-like feathers"],"~30,000"),
mk("fossa","Fossa","Cryptoprocta ferox","Mammalia","Carnivora","Eupleridae","Cryptoprocta","VU","Carnivore",15,20,6,12,"Africa","Madagascar",-18.0,47.0,"The Fossa inhabits tropical forests of Madagascar.","🐾",["More closely related to mongooses than cats","Madagascar top predator specializing in lemurs","Semi-retractable claws rare among carnivores","Can descend trees headfirst like squirrels","Ankle joints rotate 180 degrees for climbing"],"~2,600"),
mk("dugong","Dugong","Dugong dugon","Mammalia","Sirenia","Dugongidae","Dugong","VU","Herbivore",50,70,250,600,"Africa","Mozambique",-16.0,36.0,"The Dugong inhabits coastal shallows of the Indian Ocean.","🦭",["Only entirely herbivorous marine mammals","Closely related to manatees with fluked tail","Can hold breath up to 6 minutes","Believed to have inspired mermaid myths","Can consume 40 kg seagrass per day"],"~100,000"),
mk("great-hammerhead","Great Hammerhead","Sphyrna mokarran","Chondrichthyes","Carcharhiniformes","Sphyrnidae","Sphyrna","CR","Carnivore",25,35,230,450,"Africa","Senegal",14.7,-17.5,"The Great Hammerhead inhabits warm coastal waters.","🦈",["Hammer contains electrical sensors called ampullae of Lorenzini","Can grow up to 6 meters","Wide-set eyes give nearly 360-degree vision","Specializes in eating stingrays","Can give birth to litters up to 55 pups"],"~Unknown"),
mk("humpback-whale","Humpback Whale","Megaptera novaeangliae","Mammalia","Cetacea","Balaenopteridae","Megaptera","LC","Carnivore",45,100,25,40,"Africa","Mozambique",-25.0,35.0,"The Humpback Whale migrates thousands of km annually.","🐋",["Male songs last 20 minutes heard 30 km away","Migrate up to 8000 km yearly","Use cooperative bubble-net feeding","Pectoral fins reach 5 meters longest of any whale","Each tail fluke is unique like a fingerprint"],"~80,000"),
mk("african-wildcat","African Wildcat","Felis lybica","Mammalia","Carnivora","Felidae","Felis","LC","Carnivore",12,15,3,7,"Africa","South Africa",-28.0,24.0,"The African Wildcat inhabits savannas across Africa.","🐈",["All domestic cats descended from them 10000 years ago","Can still interbreed with domestic cats","Nocturnal hunters excellent rodent controllers","Reddish-brown patch on back of ears","Revered in ancient Egypt"],"~Unknown"),
mk("grey-crowned-crane","Grey Crowned Crane","Balearica regulorum","Aves","Gruiformes","Gruidae","Balearica","EN","Omnivore",22,25,3.5,4.0,"Africa","Uganda",1.0,32.0,"The Grey Crowned Crane inhabits wetlands of eastern and southern Africa.","🦩",["Famous for elaborate courtship dances","One of only two crane species that roost in trees","Golden crown feathers can be erected at will","Mate for life with synchronized calling","Wingspan can reach 2 meters"],"~50,000-100,000"),
mk("mountain-bongo","Mountain Bongo","Tragelaphus eurycerus","Mammalia","Artiodactyla","Bovidae","Tragelaphus","CR","Herbivore",15,20,200,400,"Africa","Kenya",-0.5,37.5,"The Mountain Bongo inhabits montane forests of central Kenya.","🦌",["Largest forest-dwelling antelope species","Spiraled horns reach up to 1 meter","Shy and rarely seen in the wild","Stripes help camouflage in dappled light","Fewer than 100 remain in the wild"],"~100 wild")]

# ASIA (+16)
N += [mk("gharial","Gharial","Gavialis gangeticus","Reptilia","Crocodilia","Gavialidae","Gavialis","CR","Carnivore",30,50,160,250,"Asia","India",25.0,83.0,"The Gharial inhabits rivers of the Indian subcontinent.","🐊",["Males develop a bulbous ghara on snout tip","Long narrow jaws contain over 100 needle-like teeth","Cannot walk on land due to leg positioning","Most aquatic of all crocodilians","Fewer than 1000 adults remain"],"~650"),
mk("binturong","Binturong","Arctictis binturong","Mammalia","Carnivora","Viverridae","Arctictis","VU","Omnivore",18,25,9,14,"Asia","Malaysia",4.0,102.0,"The Binturong inhabits tropical forests of Southeast Asia.","🐾",["Smells like buttered popcorn due to scent glands","One of two carnivores with fully prehensile tail","Eats mostly fruit despite being in Carnivora","Can rotate hind feet backward for climbing","Important seed disperser for fig trees"],"~Unknown"),
mk("dhole","Dhole","Cuon alpinus","Mammalia","Carnivora","Canidae","Cuon","EN","Carnivore",10,15,10,21,"Asia","India",20.0,78.0,"The Dhole inhabits forests of South and Southeast Asia.","🐕",["Can whistle to communicate across distances","Most social canids with packs up to 40","Fewer teeth than other canids","Pups eat first at a kill unlike wolves","Portrayed in Kipling's Jungle Book"],"~2,500"),
mk("green-peafowl","Green Peafowl","Pavo muticus","Aves","Galliformes","Phasianidae","Pavo","EN","Omnivore",15,20,3,5,"Asia","Cambodia",12.0,105.0,"The Green Peafowl inhabits tropical forests of Southeast Asia.","🦚",["Both sexes display colorful plumage","Strong fliers that roost in tall trees","Lost over 80% of historical range","Colors from microscopic structures not pigments","Among largest flying birds by body length"],"~15,000-30,000"),
mk("sun-bear","Malayan Sun Bear","Helarctos malayanus","Mammalia","Carnivora","Ursidae","Helarctos","VU","Omnivore",20,25,25,65,"Asia","Malaysia",4.0,102.0,"The Malayan Sun Bear inhabits tropical forests of Southeast Asia.","🐻",["Longest tongue of any bear for extracting insects","Golden chest patch unique to each individual","Most arboreal of all bear species","Powerful claws break open termite mounds","Smallest bear at 70 cm shoulder height"],"~Unknown"),
mk("indian-rhino","Indian Rhinoceros","Rhinoceros unicornis","Mammalia","Perissodactyla","Rhinocerotidae","Rhinoceros","VU","Herbivore",35,45,1800,2200,"Asia","India",26.5,89.0,"The Indian Rhinoceros inhabits floodplain grasslands of northern India.","🦏",["Single horn made of keratin like fingernails","Excellent swimmers that can dive underwater","Recovered from fewer than 200 to over 4000","Skin folds create medieval armor appearance","Can run at speeds up to 40 km/h"],"~4,000"),
mk("chinese-pangolin","Chinese Pangolin","Manis pentadactyla","Mammalia","Pholidota","Manidae","Manis","CR","Insectivore",13,20,2,7,"Asia","Nepal",27.0,85.0,"The Chinese Pangolin inhabits forests of East and South Asia.","🦔",["Most trafficked mammal on Earth","Rolls into ball even lions cannot open","Tongue extends over 40 cm from pelvis","Powerful claws dig through hard termite mounds","Scales made of keratin like human nails"],"~50,000"),
mk("water-buffalo","Asian Water Buffalo","Bubalus bubalis","Mammalia","Artiodactyla","Bovidae","Bubalus","EN","Herbivore",20,25,400,900,"Asia","Thailand",15.0,100.0,"The Asian Water Buffalo inhabits wetlands of South and Southeast Asia.","🐃",["Wild populations are ancestors of domestic breeds","Wide splayed hooves prevent sinking in mud","Can submerge almost completely underwater","Used for plowing rice paddies for 5000 years","Population declined 50% in three generations"],"~3,400 wild"),
mk("japanese-giant-salamander","Japanese Giant Salamander","Andrias japonicus","Amphibia","Urodela","Cryptobranchidae","Andrias","NT","Carnivore",30,50,15,25,"Asia","Japan",35.0,136.0,"The Japanese Giant Salamander inhabits cold mountain streams of Japan.","🐸",["Can grow up to 1.5 meters second-largest amphibian","Virtually blind detecting prey through vibrations","Breathe primarily through wrinkled skin","Unchanged for 30 million years","Can live over 50 years"],"~Unknown"),
mk("red-crowned-crane","Red-crowned Crane","Grus japonensis","Aves","Gruiformes","Gruidae","Grus","EN","Omnivore",30,40,7,10,"Asia","Japan",43.0,142.0,"The Red-crowned Crane inhabits wetlands of East Asia.","🦢",["Sacred in Japanese culture","Elaborate courtship dances with leaping","Can live up to 40 years in the wild","Calls heard several kilometers away","Second-rarest crane species"],"~3,000"),
mk("takin","Takin","Budorcas taxicolor","Mammalia","Artiodactyla","Bovidae","Budorcas","VU","Herbivore",15,20,200,350,"Asia","Bhutan",27.5,90.5,"The Takin inhabits alpine forests of the eastern Himalayas.","🐐",["Bhutan's national animal","Large nasal cavity warms cold mountain air","Skin secretions have unusual musky odor","Looks like a cross between goat and muskox","Believed to inspire the golden fleece myth"],"~Unknown"),
mk("orangutan","Bornean Orangutan","Pongo pygmaeus","Mammalia","Primates","Hominidae","Pongo","CR","Omnivore",35,45,30,90,"Asia","Malaysia",1.5,110.0,"The Bornean Orangutan inhabits rainforests of Borneo.","🦧",["Share 97% of DNA with humans","Largest tree-dwelling animals on Earth","Use tools including leaf umbrellas and sticks","Females give birth once every 6-8 years","Young stay with mothers 6-9 years"],"~104,000"),
mk("hill-myna","Common Hill Myna","Gracula religiosa","Aves","Passeriformes","Sturnidae","Gracula","LC","Omnivore",8,15,0.2,0.3,"Asia","Thailand",13.0,100.0,"The Common Hill Myna inhabits forests of South and Southeast Asia.","🐦",["One of best talking birds in the world","Bright yellow wattles distinguish from other mynas","Can mimic human speech remarkably well","Important seed disperser in tropical forests","Usually seen in pairs or small flocks"],"~Unknown"),
mk("philippine-tarsier","Philippine Tarsier","Carlito syrichta","Mammalia","Primates","Tarsiidae","Carlito","NT","Carnivore",15,20,0.08,0.15,"Asia","Philippines",10.0,124.0,"The Philippine Tarsier inhabits forests of the Philippines.","🐒",["Eyes are larger than their brain","Can rotate head 180 degrees each direction","Smallest primate by body weight 80-150g","Nocturnal hunters of insects and vertebrates","Can leap up to 5 meters between trees"],"~Unknown"),
mk("mugger-crocodile","Mugger Crocodile","Crocodylus palustris","Reptilia","Crocodilia","Crocodylidae","Crocodylus","VU","Carnivore",30,50,200,400,"Asia","Sri Lanka",7.0,80.0,"The Mugger Crocodile inhabits freshwater habitats across the Indian subcontinent.","🐊",["One of three crocodilians native to India","Can dig burrows for shelter during dry seasons","Relatively tolerant of humans","Important for controlling fish populations","Name from Hindi magar meaning water monster"],"~Unknown"),
mk("crimson-sunbird","Crimson Sunbird","Aethopyga siparaja","Aves","Passeriformes","Nectariniidae","Aethopyga","LC","Omnivore",3,5,0.006,0.012,"Asia","Singapore",1.35,103.82,"The Crimson Sunbird inhabits forests of South and Southeast Asia.","🐦",["Brilliant crimson and metallic blue plumage","Long curved bills probe deep flowers","Old World equivalent of hummingbirds","Nests are hanging pouches of plant fibers","Can hover briefly but usually perch while feeding"],"~Unknown")]

# EUROPE (+9)
N += [mk("eurasian-lynx","Eurasian Lynx","Lynx lynx","Mammalia","Carnivora","Felidae","Lynx","LC","Carnivore",12,17,15,30,"Europe","Finland",64.0,26.0,"The Eurasian Lynx inhabits forests and mountains of Europe.","🐱",["Europe's largest wild cat species","Ear tufts enhance hearing like satellite dishes","Can spot a mouse from 75 meters away","Primarily hunts hares and small ungulates","Solitary and largely nocturnal"],"~45,000"),
mk("eurasian-otter","Eurasian Otter","Lutra lutra","Mammalia","Carnivora","Mustelidae","Lutra","NT","Carnivore",10,15,6,11,"Europe","Germany",51.0,10.0,"The Eurasian Otter inhabits rivers and coastal areas of Europe.","🦦",["Excellent swimmers closing ears and nostrils underwater","Key indicator for healthy freshwater ecosystems","Can hold breath for up to 4 minutes","Fur so dense skin never gets wet","Recovered after hunting bans"],"~Unknown"),
mk("fire-salamander","Fire Salamander","Salamandra salamandra","Amphibia","Urodela","Salamandridae","Salamandra","LC","Carnivore",10,25,0.01,0.04,"Europe","Germany",50.0,8.0,"The Fire Salamander inhabits forests of central and southern Europe.","🐸",["Vivid colors warn predators of toxicity","Can secrete neurotoxic alkaloids through skin","One of few amphibians active during mild winters","Females give birth to fully formed larvae","Can reach over 20 years of age"],"~Unknown"),
mk("european-robin","European Robin","Erithacus rubecula","Aves","Passeriformes","Turdidae","Erithacus","LC","Omnivore",2,5,0.016,0.022,"Europe","United Kingdom",52.0,-1.0,"The European Robin inhabits forests and gardens across Europe.","🐦",["National bird of the United Kingdom","Unusually bold and tame around humans","Both sexes sing year-round","Highly territorial will fight other robins","Associated with Christmas in British culture"],"~Unknown"),
mk("pine-marten","Pine Marten","Martes martes","Mammalia","Carnivora","Mustelidae","Martes","LC","Omnivore",8,15,0.7,1.3,"Europe","Sweden",62.0,15.0,"The Pine Marten inhabits coniferous and mixed forests across Europe.","🦫",["Agile climbers hunting in trees and on ground","Help control invasive grey squirrel populations","Semi-retractable claws aid in climbing","Solitary and mostly nocturnal","Recovered from near extinction in parts of Britain"],"~Unknown"),
mk("wolverine","Wolverine","Gulo gulo","Mammalia","Carnivora","Mustelidae","Gulo","LC","Carnivore",7,13,10,25,"Europe","Norway",65.0,15.0,"The Wolverine inhabits arctic and subarctic Scandinavia.","🦫",["Strongest mammal relative to body size","Powerful jaws can crack frozen bone","Massive paws act like snowshoes","Can travel 30 km in a single day","Often called the skunk bear"],"~Unknown"),
mk("european-hare","European Hare","Lepus europaeus","Mammalia","Lagomorpha","Leporidae","Lepus","LC","Herbivore",4,12,3,5,"Europe","France",47.0,2.0,"The European Hare inhabits open farmland and grasslands across Europe.","🐇",["Can run at speeds up to 70 km/h","Boxing matches are courtship displays","Born with fur and eyes open unlike rabbits","Larger and longer-eared than rabbits","Populations declining in parts of Europe"],"~Unknown"),
mk("peregrine-falcon","Peregrine Falcon","Falco peregrinus","Aves","Falconiformes","Falconidae","Falco","LC","Carnivore",12,20,0.5,1.5,"Europe","United Kingdom",52.0,-2.0,"The Peregrine Falcon inhabits cliffs and cities worldwide.","🦅",["Fastest animal reaching over 320 km/h in a dive","Found on every continent except Antarctica","Adapted well to cities nesting on skyscrapers","Kill prey with impact force from high-speed stoop","Eyesight 8 times sharper than humans"],"~Unknown"),
mk("white-stork","White Stork","Ciconia ciconia","Aves","Ciconiiformes","Ciconiidae","Ciconia","LC","Carnivore",20,35,2,4,"Europe","Netherlands",52.0,5.0,"The White Stork inhabits wetlands and farmland across Europe.","🦢",["Famous for nesting on rooftops and chimneys","Migrate to Africa for winter","Clatter bills as primary communication","Believed to deliver babies in folklore","Can have wingspan over 2 meters"],"~Unknown")]
