#!/usr/bin/env python3
"""Expand animals.json to 200+ animals with upgraded emojis."""
import json

with open("src/data/animals.json") as f:
    animals = json.load(f)

existing_slugs = {a["slug"] for a in animals}

CC = {
    "South Africa":"za","Kenya":"ke","Tanzania":"tz","Madagascar":"mg","Egypt":"eg",
    "Uganda":"ug","Namibia":"na","Botswana":"bw","Morocco":"ma","Ethiopia":"et",
    "Rwanda":"rw","Congo":"cd","Nigeria":"ng","Cameroon":"cm","Ghana":"gh",
    "Senegal":"sn","Zimbabwe":"zw","Mozambique":"mz","Zambia":"zm","Malawi":"mw",
    "India":"in","Japan":"jp","Philippines":"ph","Sri Lanka":"lk","Malaysia":"my",
    "Thailand":"th","Vietnam":"vn","Myanmar":"mm","Brunei":"bn","Cambodia":"kh",
    "North Korea":"kp","Taiwan":"tw","Pakistan":"pk","Nepal":"np","Indonesia":"id",
    "China":"cn","Bangladesh":"bd","Mongolia":"mn","South Korea":"kr","Laos":"la",
    "Maldives":"mv","Christmas Island":"cx","Singapore":"sg","Bhutan":"bt",
    "Brazil":"br","Mexico":"mx","Canada":"ca","United States":"us","Peru":"pe",
    "Colombia":"co","Ecuador":"ec","Chile":"cl","Argentina":"ar","Costa Rica":"cr",
    "Panama":"pa","Bolivia":"bo","Venezuela":"ve","Paraguay":"py","Uruguay":"uy",
    "Guyana":"gy","United Kingdom":"gb","France":"fr","Germany":"de","Sweden":"se",
    "Norway":"no","Spain":"es","Italy":"it","Greece":"gr","Poland":"pl","Romania":"ro",
    "Iceland":"is","Finland":"fi","Switzerland":"ch","Portugal":"pt","Netherlands":"nl",
    "Belgium":"be","Denmark":"dk","Ireland":"ie","Croatia":"hr","Austria":"at",
    "Australia":"au","New Zealand":"nz","Papua New Guinea":"pg","Fiji":"fj",
    "Samoa":"ws","Tonga":"to","French Polynesia":"pf","Guam":"gu","New Caledonia":"nc",
    "Saudi Arabia":"sa","United Arab Emirates":"ae","Oman":"om","Israel":"il",
    "Jordan":"jo","Yemen":"ye","Iraq":"iq","Iran":"ir","Kuwait":"kw","Turkey":"tr",
    "Svalbard":"sj","Greenland":"gl","Antarctica":"aq","Russia":"ru",
}

def flag(country):
    c = CC.get(country, "xx")
    return "".join(chr(0x1F1E6+ord(x)-97) for x in c)

def iucn_lbl(s):
    return {"EX":"Extinct","EW":"Extinct in the Wild","CR":"Critically Endangered",
            "EN":"Endangered","VU":"Vulnerable","NT":"Near Threatened",
            "LC":"Least Concern","DD":"Data Deficient","NE":"Not Evaluated"}.get(s,s)

def animal(slug, common, sci, klass, order, family, genus, iucn, diet,
           lmin, lmax, wmin, wmax, region, country, lat, lng, desc, hab, emoji,
           facts, pop="", phylum="Chordata"):
    cls = klass
    return {
        "id": CC.get(country,"xx"), "slug": slug, "commonName": common,
        "scientificName": sci,
        "taxonomy": {"kingdom":"Animalia","phylum":phylum,"class":klass,
                     "order":order,"family":family,"genus":genus},
        "iucnStatus": iucn, "description": desc,
        "habitat": [hab.lower()], "diet": diet,
        "lifespan": {"min":lmin,"max":lmax,"unit":"years"},
        "weight": {"min":wmin,"max":wmax,"unit":"kg"},
        "nativeRegions": [region],
        "coordinates": [{"lat":lat,"lng":lng,"label":country}],
        "images": [], "funFacts": facts,
        "wikiUrl": f"https://en.wikipedia.org/wiki/{common.replace(' ','_')}",
        "updatedAt": "2026-04-17T00:00:00Z",
        "country": country, "flag": flag(country), "region": region,
        "animal": common, "emoji": emoji,
        "classification": "Mammal" if klass=="Mammalia" else "Bird" if klass=="Aves" else "Reptile" if klass=="Reptilia" else "Amphibian" if klass=="Amphibia" else "Fish" if klass in ("Chondrichthyes","Actinopterygii") else "Insect",
        "conservationStatus": iucn_lbl(iucn), "indigenous": True,
        "habitatOld": hab, "population": pop
    }

N = []

# AFRICA additions
N += [animal("african-penguin","African Penguin","Spheniscus demersus","Aves","Sphenisciformes","Spheniscidae","Spheniscus","EN","Piscivore",10,20,2,5,"Africa","South Africa",-33.92,18.42,"The African Penguin is the only penguin species that breeds in Africa, found along the coastlines of South Africa and Namibia.","Rocky coastlines and islands of South Africa and Namibia","🐧",["Also called the jackass penguin due to its braying call","Can dive to depths over 130 meters to catch fish","Have a pink gland above their eyes that helps regulate body temperature","They pair for life and return to the same nesting site each year","Oil spills are one of their greatest threats"],"~25,000 pairs"),
animal("grevys-zebra","Grevy's Zebra","Equus grevyi","Mammalia","Perissodactyla","Equidae","Equus","EN","Herbivore",20,25,350,450,"Africa","Kenya",0.59,37.0,"Grevy's Zebra is the largest and most endangered zebra species, with narrow stripes and large ears.","Semi-arid grasslands of Kenya and Ethiopia","🦓",["Stripes are much narrower than other zebra species","Ears are larger and more rounded than plains zebras","Can survive up to five days without water","Males hold large territories in their social structure","Fewer than 3,000 remain in the wild"],"~3,000"),
animal("okapi","Okapi","Okapia johnstoni","Mammalia","Artiodactyla","Giraffidae","Okapia","EN","Herbivore",20,30,200,350,"Africa","Congo",0.23,29.0,"The Okapi is a giraffe relative found only in Congo's rainforests, unknown to Western science until 1901.","Dense tropical rainforest of the Congo Basin","🦒",["Only living relative of the giraffe","Striped hindquarters help calves follow mothers through dark forest","Prehensile tongues are long enough to wash their own eyelids","Communicate using infrasound too low for humans to hear","Named after explorer Sir Harry Johnston"],"~35,000"),
animal("shoebill","Shoebill","Balaeniceps rex","Aves","Pelecaniformes","Balaenicipitidae","Balaeniceps","VU","Carnivore",30,35,4,7,"Africa","Uganda",1.37,32.29,"The Shoebill is a large stork-like bird with a massive shoe-shaped bill found in East African swamps.","Papyrus swamps and marshlands of East Africa","🦢",["Bill can measure up to 24 centimeters in length","Stand motionless for hours while hunting fish","Can decapitate prey before swallowing","Clatter bills rapidly as communication during nesting","Depicted in ancient Egyptian artwork"],"~5,000-8,000"),
animal("nile-crocodile","Nile Crocodile","Crocodylus niloticus","Reptilia","Crocodilia","Crocodylidae","Crocodylus","LC","Carnivore",50,80,200,750,"Africa","Kenya",-1.29,36.82,"The Nile Crocodile is Africa's largest freshwater predator, virtually unchanged for millions of years.","Rivers, lakes, and marshlands across sub-Saharan Africa","🐊",["Strongest bite force ever measured in a living animal","Can hold breath underwater for up to 2 hours at rest","Females carry hatchlings to water in their mouths","Can grow up to 5 meters long","Known to take prey as large as hippos"],"~500,000"),
animal("african-grey-parrot","African Grey Parrot","Psittacus erithacus","Aves","Psittaciformes","Psittacidae","Psittacus","EN","Omnivore",40,60,0.3,0.6,"Africa","Cameroon",5.0,11.0,"The African Grey Parrot is renowned for exceptional intelligence and ability to mimic human speech.","Lowland rainforests of West and Central Africa","🦜",["Can understand concepts like color, shape, and number","Can learn vocabularies of over 1,000 words","Live in large flocks and are highly social","Cognitive abilities comparable to a 5-year-old child","Wild populations declined severely due to pet trade"],"~630,000"),
animal("mandrill","Mandrill","Mandrillus sphinx","Mammalia","Primates","Cercopithecidae","Mandrillus","VU","Omnivore",20,30,20,50,"Africa","Cameroon",4.0,13.0,"The Mandrill is the world's largest monkey, famous for the male's vivid blue and red facial coloring.","Tropical rainforests of Central Africa","🐵",["Most colorful faces of any mammal","Color intensity indicates testosterone and social rank","Troops can contain up to 1,000 individuals","Have cheek pouches that store food equal to stomach capacity","Despite intimidating appearance, they are shy and avoid humans"],"~100,000"),
animal("pangolin-africa","Ground Pangolin","Manis temminckii","Mammalia","Pholidota","Manidae","Manis","EN","Insectivore",13,20,7,18,"Africa","South Africa",-25.0,27.0,"The Ground Pangolin is a scaly anteater that curls into a ball when threatened.","Savannas, woodlands, and grasslands of sub-Saharan Africa","🦔",["Only mammals entirely covered in keratin scales","Consume up to 70 million ants and termites per year","Have no teeth, using muscular stomach with ingested pebbles","Most trafficked mammals in the world","Tongue can be longer than entire body"],"~100,000"),
animal("aardvark","Aardvark","Orycteropus afer","Mammalia","Tubulidentata","Orycteropodidae","Orycteropus","LC","Insectivore",18,23,40,80,"Africa","South Africa",-29.0,24.0,"The Aardvark is a nocturnal burrowing mammal whose name means 'earth pig' in Afrikaans.","Savannas, grasslands, and forests of sub-Saharan Africa","🐗",["Can dig up to 0.5 meters of soil in 15 seconds","Only living species in order Tubulidentata","Tongue can be up to 30 cm long coated in sticky saliva","Eats about 50,000 termites per night","Burrows provide shelter for warthogs, hyenas, and others"],"~Unknown"),
animal("gelada","Gelada","Theropithecus gelada","Mammalia","Primates","Cercopithecidae","Theropithecus","EN","Herbivore",15,20,15,25,"Africa","Ethiopia",10.0,39.0,"The Gelada is a grass-eating primate found only in the Ethiopian Highlands, called the bleeding-heart monkey.","Alpine grasslands of the Ethiopian Highlands","🐒",["Only primates that are primarily grazers","Red chest patch indicates health and dominance","Form the largest primate troops sometimes exceeding 1,000 individuals","Spend more time on ground than any other primate except humans","Complex vocal repertoire with over 30 distinct calls"],"~200,000"),
animal("caracal","Caracal","Caracal caracal","Mammalia","Carnivora","Felidae","Caracal","LC","Carnivore",12,15,8,20,"Africa","South Africa",-30.0,25.0,"The Caracal is a medium-sized wild cat known for distinctive tufted ears.","Arid regions, savannas, and woodlands of Africa","🐾",["Can leap up to 3 meters to catch birds in flight","Ear tufts may help detect prey sounds","Ancient Egyptians used trained caracals for hunting","Solitary and highly territorial","Can survive without drinking by getting moisture from prey"],"~Unknown"),
animal("secretary-bird","Secretary Bird","Sagittarius serpentarius","Aves","Accipitriformes","Sagittariidae","Sagittarius","EN","Carnivore",15,20,3,5,"Africa","Kenya",-1.0,37.0,"The Secretary Bird is a large bird of prey that hunts snakes by stomping on them with incredible force.","Open grasslands and savannas of sub-Saharan Africa","🦅",["Can deliver kicks with force of 5-6 times body weight","Only bird of prey that primarily hunts on foot","Scientific name means 'archer of snakes'","Can cover 20-30 km per day on foot patrolling territory","Name may come from quill-like feathers behind their head"],"~30,000"),
animal("fossa","Fossa","Cryptoprocta ferox","Mammalia","Carnivora","Eupleridae","Cryptoprocta","VU","Carnivore",15,20,6,12,"Africa","Madagascar",-18.0,47.0,"The Fossa is Madagascar's largest carnivorous mammal, specializing in hunting lemurs.","Tropical forests of Madagascar","🐾",["More closely related to mongooses than to cats","Madagascar's top predator specializing in hunting lemurs","Semi-retractable claws, rare among carnivores","Can descend trees headfirst like squirrels","Ankle joints rotate 180 degrees for climbing"],"~2,600"),
animal("dugong","Dugong","Dugong dugon","Mammalia","Sirenia","Dugongidae","Dugong","VU","Herbivore",50,70,250,600,"Africa","Mozambique",-16.0,36.0,"The Dugong is a large marine mammal that feeds exclusively on seagrass, often called a sea cow.","Coastal shallow waters of the Indian and Pacific Oceans","🦭",["Only entirely herbivorous marine mammals in existence","Closely related to manatees but have fluked tail like a whale","Can hold breath for up to 6 minutes","Believed to have inspired myths about mermaids","Can consume up to 40 kg of seagrass per day"],"~100,000"),
animal("hammerhead-shark","Great Hammerhead","Sphyrna mokarran","Chondrichthyes","Carcharhiniformes","Sphyrnidae","Sphyrna","CR","Carnivore",25,35,230,450,"Africa","Senegal",14.7,-17.5,"The Great Hammerhead is the largest hammerhead shark, using its hammer-shaped head for sensory detection.","Warm coastal waters worldwide","🦈",["Hammer head contains electrical sensors called ampullae of Lorenzini","Can grow up to 6 meters in length","Wide-set eyes give nearly 360-degree vision","Known to eat stingrays, pinned to ocean floor before consuming","Can give birth to litters of up to 55 pups"],"~Unknown"),
animal("humpback-whale-moz","Humpback Whale","Megaptera novaeangliae","Mammalia","Cetacea","Balaenopteridae","Megaptera","LC","Carnivore",45,100,25,40,"Africa","Mozambique",-25.0,35.0,"The Humpback Whale is known for breaching and complex songs, migrating thousands of km annually.","Oceans worldwide","🐋",["Male songs can last 20 minutes and be heard 30 km away","Migrate up to 8,000 km yearly between feeding and breeding grounds","Use cooperative bubble-net feeding to corral fish","Pectoral fins reach up to 5 meters, longest of any whale","Each tail fluke pattern is unique like a fingerprint"],"~80,000"),
animal("african-wildcat","African Wildcat","Felis lybica","Mammalia","Carnivora","Felidae","Felis","LC","Carnivore",12,15,3,7,"Africa","South Africa",-28.0,24.0,"The African Wildcat is the ancestor of all domestic cats, nearly identical in appearance to a tabby.","Savannas, scrublands, and forests across Africa","🐈",["All domestic cats descended from African wildcats ~10,000 years ago","Can still interbreed with domestic cats","Nocturnal hunters and excellent rodent controllers","Distinctive reddish-brown patch on back of ears","Revered in ancient Egypt, associated with goddess Bastet"],"~Unknown"),
animal("grey-crowned-crane","Grey Crowned Crane","Balearica regulorum","Aves","Gruiformes","Gruidae","Balearica","EN","Omnivore",22,25,3.5,4.0,"Africa","Uganda",1.0,32.0,"The Grey Crowned Crane is an iconic African bird with a golden crown, Uganda's national bird.","Wetlands and grasslands of eastern and southern Africa","🦩",["Famous for elaborate courtship dances","Can roost in trees, rare among cranes","One of only two crane species that perch in trees","Golden crown feathers can be erected at will","Mate for life with synchronized calling displays"],"~50,000-100,000"),
animal("vulture-africa","Lappet-faced Vulture","Torgos tracheliotos","Aves","Accipitriformes","Accipitridae","Torgos","EN","Carnivore",20,50,5,9,"Africa","Tanzania",-3.0,35.0,"The Lappet-faced Vulture is Africa's largest vulture, a powerful scavenger that dominates at carcasses.","Arid savannas and deserts of sub-Saharan Africa","🦅",["Wingspan reaches up to 2.9 meters","Face skin folds called lappets help regulate temperature","Powerful bill can tear through tough hide and even small bones","Often first to arrive at carcasses despite not being fastest","Population declined dramatically due to poisoning"],"~8,500"),
animal("bongo","Mountain Bongo","Tragelaphus eurycerus","Mammalia","Artiodactyla","Bovidae","Tragelaphus","CR","Herbivore",15,20,200,400,"Africa","Kenya",-0.5,37.5,"The Mountain Bongo is a large forest antelope with striking chestnut-red coat and white stripes.","Montane forests of central Kenya","🦌",["Largest forest-dwelling antelope species","Spiraled horns can reach up to 1 meter in length","Shy and elusive, rarely seen in the wild","Stripes help camouflage in dappled forest light","Fewer than 100 remain in the wild"],"~100 wild"),
]

# ASIA additions
N += [animal("gharial","Gharial","Gavialis gangeticus","Reptilia","Crocodilia","Gavialidae","Gavialis","CR","Carnivore",30,50,160,250,"Asia","India",25.0,83.0,"The Gharial is a critically endangered crocodilian with a long thin snout adapted for catching fish.","Rivers of the Indian subcontinent","🐊",["Males develop a bulbous ghara growth on snout tip","Long narrow jaws contain over 100 needle-like teeth","Cannot walk on land due to leg positioning","Most aquatic of all crocodilians","Fewer than 1,000 adults remain in the wild"],"~650"),
animal("binturong","Binturong","Arctictis binturong","Mammalia","Carnivora","Viverridae","Arctictis","VU","Omnivore",18,25,9,14,"Asia","Malaysia",4.0,102.0,"The Binturong or bearcat is a large viverrid, one of only two carnivores with a prehensile tail.","Tropical forests of Southeast Asia","🐾",["Smells like buttered popcorn due to scent gland secretion","One of two carnivore species with fully prehensile tail","Eats mostly fruit despite being in Carnivora order","Can rotate hind feet backward for climbing down headfirst","Important seed disperser for fig trees"],"~Unknown"),
animal("dhole","Dhole","Cuon alpinus","Mammalia","Carnivora","Canidae","Cuon","EN","Carnivore",10,15,10,21,"Asia","India",20.0,78.0,"The Dhole is a highly social wild dog that hunts cooperatively in large packs.","Forests, grasslands, and mountains of South and Southeast Asia","🐕",["Can whistle to communicate across long distances","Most social of all canids with packs up to 40","Fewer teeth than other canids, specialized for meat-eating","Unlike wolves, pups eat first at a kill","Portrayed as antagonists in Kipling's Jungle Book"],"~2,500"),
animal("green-peafowl","Green Peafowl","Pavo muticus","Aves","Galliformes","Phasianidae","Pavo","EN","Omnivore",15,20,3,5,"Asia","Cambodia",12.0,105.0,"The Green Peafowl has vivid green and blue plumage in both sexes, unlike the Indian Peafowl.","Tropical forests of Southeast Asia","🦚",["Both sexes display colorful plumage","Strong fliers that roost in tall trees","Lost over 80% of their historical range","Colors produced by microscopic structures not pigments","Among the largest flying birds by body length"],"~15,000-30,000"),
animal("sun-bear","Malayan Sun Bear","Helarctos malayanus","Mammalia","Carnivora","Ursidae","Helarctos","VU","Omnivore",20,25,25,65,"Asia","Malaysia",4.0,102.0,"The Malayan Sun Bear is the smallest bear, named for its golden crescent-shaped chest patch.","Tropical evergreen forests of Southeast Asia","🐻",["Longest tongue of any bear for extracting honey and insects","Golden chest patch unique to each individual like a fingerprint","Most arboreal of all bear species","Powerful claws break open termite mounds and bee nests","Smallest bear species at about 70 cm shoulder height"],"~Unknown"),
animal("indian-rhino","Indian Rhinoceros","Rhinoceros unicornis","Mammalia","Perissodactyla","Rhinocerotidae","Rhinoceros","VU","Herbivore",35,45,1800,2200,"Asia","India",26.5,89.0,"The Indian Rhinoceros has a single horn and skin folds resembling armor plating.","Floodplain grasslands of northern India and Nepal","🦏",["Single horn made of keratin like fingernails","Excellent swimmers that can dive and feed underwater","Recovered from fewer than 200 to over 4,000 individuals","Skin folds create appearance of medieval armor","Can run at speeds up to 40 km/h"],"~4,000"),
animal("crimson-sunbird","Crimson Sunbird","Aethopyga siparaja","Aves","Passeriformes","Nectariniidae","Aethopyga","LC","Omnivore",3,5,0.006,0.012,"Asia","Singapore",1.35,103.82,"The Crimson Sunbird is a tiny vividly colored bird, the Old World equivalent of hummingbirds.","Tropical forests of South and Southeast Asia","🐦",["Male has brilliant crimson and metallic blue breeding plumage","Long curved bills probe deep flowers for nectar","Old World ecological equivalent of hummingbirds","Can hover briefly but usually perch while feeding","Nests are hanging pouches of plant fibers and spider silk"],"~Unknown"),
animal("chinese-pangolin","Chinese Pangolin","Manis pentadactyla","Mammalia","Pholidota","Manidae","Manis","CR","Insectivore",13,20,2,7,"Asia","Nepal",27.0,85.0,"The Chinese Pangolin is a critically endangered scaly anteater, the most trafficked mammal on Earth.","Forests of East and South Asia","🦔",["Most trafficked mammal species on Earth","Roll into ball that even lions cannot open","Scales made of keratin like human hair and nails","Tongue attached near pelvis extending over 40 cm","Powerful claws dig through hard termite mounds"],"~50,000"),
animal("water-buffalo","Asian Water Buffalo","Bubalus bubalis","Mammalia","Artiodactyla","Bovidae","Bubalus","EN","Herbivore",20,25,400,900,"Asia","Thailand",15.0,100.0,"The Asian Water Buffalo is well-adapted to wet environments, ancestors of all domesticated breeds.","Wetlands and floodplains of South and Southeast Asia","🐃",["Wild populations are ancestors of all domestic water buffalo","Wide splayed hooves prevent sinking in mud","Can submerge almost completely underwater","Used for plowing rice paddies for over 5,000 years","Wild population declined 50% in three generations"],"~3,400 wild"),
animal("giant-salamander","Japanese Giant Salamander","Andrias japonicus","Amphibia","Urodela","Cryptobranchidae","Andrias","NT","Carnivore",30,50,15,25,"Asia","Japan",35.0,136.0,"The Japanese Giant Salamander is one of the largest amphibians, a 30-million-year-old living fossil.","Cold mountain streams of Japan","🦎",["Can grow up to 1.5 meters, second-largest salamander","Virtually blind, detect prey through vibrations and smell","Breathe primarily through wrinkled skin","Nocturnal, can live over 50 years","Living fossil unchanged for 30 million years"],"~Unknown"),
animal("red-crowned-crane","Red-crowned Crane","Grus japonensis","Aves","Gruiformes","Gruidae","Grus","EN","Omnivore",30,40,7,10,"Asia","Japan",43.0,142.0,"The Red-crowned Crane symbolizes longevity and fidelity in East Asian culture.","Wetlands and marshes of East Asia","🦢",["Sacred in Japanese culture symbolizing longevity","Elaborate courtship dances with leaping and bowing","Can live up to 40 years in the wild","Calls heard several kilometers away","Second-rarest crane with about 3,000 individuals"],"~3,000"),
animal("takin","Takin","Budorcas taxicolor","Mammalia","Artiodactyla","Bovidae","Budorcas","VU","Herbivore",15,20,200,350,"Asia","Bhutan",27.5,90.5,"The Takin is a large goat-antelope found in the eastern Himalayas, Bhutan's national animal.","Alpine forests and meadows of the eastern Himalayas","🐐",["Bhutan's national animal","Looks like a cross between a goat and a muskox","Large nasal cavity warms cold mountain air before reaching lungs","Secretions from skin have unusual musky odor","Believed to be the inspiration for the golden fleece myth"],"~Unknown"),
animal("orangutan","Bornean Orangutan","Pongo pygmaeus","Mammalia","Primates","Hominidae","Pongo","CR","Omnivore",35,45,30,90,"Asia","Malaysia",1.5,110.0,"The Bornean Orangutan is a great ape sharing 97% of DNA with humans, native to Borneo.","Tropical rainforests of Borneo","🦧",["Share approximately 97% of DNA with humans","Largest tree-dwelling animals on Earth","Use tools in the wild including leaf umbrellas and sticks","Females give birth only once every 6-8 years","Young stay with mothers for 6-9 years, longest of any mammal except humans"],"~104,000"),
animal("muntjac","Indian Muntjac","Muntiacus muntjak","Mammalia","Artiodactyla","Cervidae","Muntiacus","LC","Omnivore",15,20,15,35,"Asia","India",22.0,82.0,"The Indian Muntjac, also called barking deer, is a small deer known for its dog-like alarm calls.","Forests of South and Southeast Asia","🦌",["Called barking deer due to their sharp dog-like alarm calls","Have scent glands below their eyes used for marking territory","Males have short antlers and visible tusk-like canines","Oldest known deer species, dating back 15-35 million years","Extremely adaptable and can survive near human settlements"],"~Unknown"),
animal("myna-bird","Common Hill Myna","Gracula religiosa","Aves","Passeriformes","Sturnidae","Gracula","LC","Omnivore",8,15,0.2,0.3,"Asia","Thailand",13.0,100.0,"The Common Hill Myna is a glossy black bird with bright yellow wattles, renowned for its talking ability.","Forests of South and Southeast Asia","🐦",["One of the best talking birds in the world","Bright yellow wattles distinguish it from other mynas","Can mimic human speech with remarkable clarity","Usually seen in pairs or small flocks","Important role in seed dispersal in tropical forests"],"~Unknown"),
animal("monarch-butterfly-asia","Tiger Swallowtail","Papilio machaon","Insecta","Lepidoptera","Papilionidae","Papilio","LC","Herbivore",1,2,0.001,0.003,"Asia","Japan",36.0,140.0,"The Asian Swallowtail butterfly is widespread across temperate Asia, known for its striking yellow and black wings.","Temperate meadows and forests of Asia","🦋",["Wingspan reaches up to 9 cm","One of the most widespread butterfly species in the world","Caterpillars have eyespots to scare predators","Can be found from sea level to mountain meadows","Important pollinator in temperate ecosystems"],"~Unknown","Arthropoda"),
animal("asian-elephant-india","Asian Elephant","Elephas maximus","Mammalia","Proboscidea","Elephantidae","Elephas","EN","Herbivore",48,65,2700,4000,"Asia","India",11.0,78.0,"The Asian Elephant is the largest land animal in Asia, highly intelligent with complex social structures.","Tropical and subtropical forests of South and Southeast Asia","🐘",["Asian elephants have smaller ears than African elephants","Trunk contains over 40,000 muscles","Highly intelligent, can recognize themselves in mirrors","Form complex matriarchal societies","Domesticated for thousands of years in Asian cultures"],"~48,000 wild"),
]

# EUROPE additions
N += [animal("eurasian-lynx","Eurasian Lynx","Lynx lynx","Mammalia","Carnivora","Felidae","Lynx","LC","Carnivore",12,17,15,30,"Europe","Finland",64.0,26.0,"The Eurasian Lynx is Europe's largest wild cat, recognizable by its distinctive ear tufts.","Forests and mountainous areas of Europe and Asia","🐱",["Europe's largest wild cat species","Ear tufts enhance hearing like satellite dishes","Can spot a mouse from 75 meters away","Primarily hunts hares and small ungulates","Solitary and largely nocturnal"],"~45,000"),
animal("european-otter","Eurasian Otter","Lutra lutra","Mammalia","Carnivora","Mustelidae","Lutra","NT","Carnivore",10,15,6,11,"Europe","Germany",51.0,10.0,"The Eurasian Otter is a semi-aquatic mammal found across Europe's waterways, a key indicator of clean water.","Rivers, lakes, and coastal areas of Europe","🦦",["Excellent swimmers that can close their ears and nostrils underwater","Key indicator species for healthy freshwater ecosystems","Can hold breath for up to 4 minutes while diving","Fur is so dense that skin never gets wet","Recovered significantly after hunting bans and pollution controls"],"~Unknown"),
animal("fire-salamander","Fire Salamander","Salamandra salamandra","Amphibia","Urodela","Salamandridae","Salamandra","LC","Carnivore",10,25,0.01,0.04,"Europe","Germany",50.0,8.0,"The Fire Salamander is Europe's most iconic amphibian, recognized by its vivid black and yellow warning colors.","Forests of central and southern Europe","🦎",["Vivid black and yellow colors warn predators of toxicity","Can secrete neurotoxic alkaloids through their skin","One of few amphibians active during winter in mild climates","Females give birth to fully formed larvae in water","Longest-lived salamanders, can reach 20+ years"],"~Unknown","Chordata"),
animal("european-robin","European Robin","Erithacus rubecula","Aves","Passeriformes","Turdidae","Erithacus","LC","Omnivore",2,5,0.016,0.022,"Europe","United Kingdom",52.0,-1.0,"The European Robin is a beloved garden bird across Europe, famous for its bold behavior near humans.","Forests, gardens, and parks across Europe","🐦",["National bird of the United Kingdom","Unusually bold and tame around humans","Both males and females sing year-round, not just during breeding","Territorial and will fight other robins to defend territory","Associated with Christmas in British culture"],"~Unknown"),
animal("pine-marten","Pine Marten","Martes martes","Mammalia","Carnivora","Mustelidae","Martes","LC","Omnivore",8,15,0.7,1.3,"Europe","Sweden",62.0,15.0,"The Pine Marten is a agile tree-climbing mustelid found in forests across Europe.","Coniferous and mixed forests of Europe","🦫",["Agile climbers that hunt both in trees and on the ground","Help control invasive grey squirrel populations in the UK","Semi-retractable claws aid in climbing","Solitary and mostly nocturnal","Recovered from near extinction in parts of Britain"],"~Unknown"),
animal("wolverine-eu","Wolverine","Gulo gulo","Mammalia","Carnivora","Mustelidae","Gulo","LC","Carnivore",7,13,10,25,"Europe","Norway",65.0,15.0,"The Wolverine is the largest terrestrial mustelid, known for tremendous strength relative to its size.","Arctic and subarctic regions including Scandinavia","🦫",["Strongest mammal relative to body size, can take prey 5x its weight","Powerful jaws can crack frozen bone","Massive paws act like snowshoes for winter travel","Can travel 30 km in a single day foraging","Often called the skunk bear due to marking behavior"],"~Unknown"),
animal("european-hare","European Hare","Lepus europaeus","Mammalia","Lagr